import { StyleSheet, Platform, Dimensions } from 'react-native';

const BG = '#0A0F1E';
const CARD_BG = '#1A1F2E';
const BORDER = 'rgba(255,255,255,0.06)';
const GREEN = '#00C896';
const RED = '#FF4D4F';

const shadow = Platform.select({
    ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
    },
    android: {
        elevation: 4,
    },
});

const windowHeight = Dimensions.get('window').height;

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: BG,
    },
    container: {
        flex: 1,
        paddingHorizontal: 16,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingTop: 5,
        marginBottom: 8,

    },
    backButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerCenter: {
        flex: 1,
        alignItems: 'center',
    },
    headerTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    notificationButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
    },
    notificationBadge: {
        position: 'absolute',
        top: 8,
        right: 8,
        backgroundColor: RED,
        borderRadius: 10,
        minWidth: 20,
        height: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    notificationBadgeText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
    },
    descriptionBox: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: GREEN,
        ...shadow,
    },
    descriptionIcon: {
        backgroundColor: '#232834',
        borderRadius: 30,
        padding: 12,
        marginRight: 16,
    },
    descriptionContent: {
        flex: 1,
    },
    descriptionTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 4,
    },
    descriptionText: {
        color: '#aaa',
        fontSize: 14,
        lineHeight: 20,
    },
    newToCryptoBox: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    newToCryptoIcon: {
        backgroundColor: '#232834',
        borderRadius: 30,
        padding: 12,
        marginRight: 16,
    },
    newToCryptoContent: {
        flex: 1,
    },
    newToCryptoTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 4,
    },
    newToCryptoText: {
        color: '#aaa',
        fontSize: 14,
        lineHeight: 20,
    },
    p2pButton: {
        backgroundColor: GREEN,
        borderRadius: 10,
        paddingHorizontal: 16,
        paddingVertical: 8,
        marginLeft: 12,
    },
    p2pButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
    alreadyKnowCryptoBox: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    alreadyKnowCryptoIcon: {
        backgroundColor: '#232834',
        borderRadius: 30,
        padding: 12,
        marginRight: 16,
    },
    alreadyKnowCryptoContent: {
        flex: 1,
    },
    alreadyKnowCryptoTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 4,
    },
    alreadyKnowCryptoText: {
        color: '#aaa',
        fontSize: 14,
        lineHeight: 20,
    },
    depositButton: {
        backgroundColor: GREEN,
        borderRadius: 10,
        paddingHorizontal: 16,
        paddingVertical: 8,
        marginLeft: 12,
    },
    depositButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
    toggleContainer: {
        backgroundColor: CARD_BG,
        borderRadius: 12,
        padding: 4,
        marginBottom: 20,
        flexDirection: 'row',
        position: 'relative',
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    toggleButton: {
        flex: 1,
        paddingVertical: 12,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 8,
        zIndex: 2,
    },
    toggleButtonActive: {
        backgroundColor: 'transparent',
    },
    toggleText: {
        color: '#aaa',
        fontSize: 16,
        fontWeight: '600',
    },
    toggleTextActive: {
        color: '#fff',
    },
    greenBar: {
        position: 'absolute',
        top: 4,
        width: '50%',
        height: 'calc(100% - 8px)',
        backgroundColor: GREEN,
        borderRadius: 8,
        zIndex: 1,
    },
    section: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    sectionTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 12,
    },
    amountContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(35,40,52,0.5)',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    amountInput: {
        flex: 1,
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        backgroundColor: 'transparent',
    },
    currencyLabel: {
        color: GREEN,
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 12,
    },
    selector: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(35,40,52,0.5)',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    selectorContent: {
        flex: 1,
    },
    selectorText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '500',
    },
    placeholderText: {
        color: '#aaa',
        fontSize: 16,
        fontWeight: '400',
    },
    continueButtonContainer: {
        marginHorizontal: 16,
        marginBottom: 32,
    },
    continueButton: {
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 16,
        alignItems: 'center',
        justifyContent: 'center',
        ...shadow,
    },
    continueButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    modalOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    modalBlur: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: CARD_BG,
        borderRadius: 20,
        margin: 20,
        width: '90%',
        maxHeight: '80%',
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: BORDER,
    },
    modalTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    modalList: {
        maxHeight: windowHeight * 0.6,
    },
    modalItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: BORDER,
    },
    modalItemContent: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    modalItemLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    methodIcon: {
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderRadius: 12,
        padding: 8,
        marginRight: 12,
    },
    modalItemName: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '500',
        marginBottom: 2,
    },
    modalItemSubtext: {
        color: '#aaa',
        fontSize: 14,
    },
    modalItemPrice: {
        color: GREEN,
        fontSize: 16,
        fontWeight: 'bold',
    },
}); 