import { StyleSheet, Platform } from 'react-native';

const BG = '#0A0F1E';
const CARD_BG = '#1A1F2E';
const BORDER = 'rgba(255,255,255,0.06)';
const GREEN = '#00C896';
const RED = '#FF4D4F';

const shadow = Platform.select({
    ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
    },
    android: {
        elevation: 4,
    },
});


export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: BG,
    },
    container: {
        flex: 1,
        paddingHorizontal: 16,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingHorizontal: 20,
        paddingVertical: 16,
        paddingTop: 5,
        marginBottom: 8,
    },
    backButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    descriptionBox: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: GREEN,
        ...shadow,
    },
    descriptionIcon: {
        backgroundColor: '#232834',
        borderRadius: 30,
        padding: 12,
        marginRight: 16,
    },
    descriptionContent: {
        flex: 1,
    },
    descriptionTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 4,
    },
    descriptionText: {
        color: '#aaa',
        fontSize: 14,
        lineHeight: 20,
    },
    infoSection: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    infoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
    },
    infoLabel: {
        color: '#aaa',
        fontSize: 14,
        fontWeight: '500',
    },
    infoValue: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
    amountContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(35,40,52,0.5)',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    amountInput: {
        flex: 1,
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        backgroundColor: 'transparent',
    },
    currencyLabel: {
        color: GREEN,
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 12,
    },
    depositButtonContainer: {
        marginHorizontal: 16,
        marginBottom: 32,
    },
    depositButton: {
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 16,
        alignItems: 'center',
        justifyContent: 'center',
        ...shadow,
    },
    depositButtonDisabled: {
        backgroundColor: 'rgba(0,200,150,0.3)',
    },
    depositButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    depositButtonTextDisabled: {
        color: 'rgba(255,255,255,0.5)',
    },
    section: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    sectionTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 12,
    },
    addressContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(35,40,52,0.5)',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
        marginBottom: 12,
    },
    addressBox: {
        flex: 1,
        marginRight: 12,
    },
    addressText: {
        color: '#fff',
        fontSize: 14,
        fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    },
    copyButton: {
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderRadius: 8,
        padding: 8,
    },
    qrButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: 'rgba(0,200,150,0.3)',
    },
    qrButtonText: {
        color: GREEN,
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 8,
    },
    importantNotes: {
        backgroundColor: 'rgba(255,77,79,0.1)',
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,77,79,0.2)',
    },
    importantTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 12,
    },
    noteItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 8,
    },
    noteBullet: {
        color: RED,
        fontSize: 16,
        marginRight: 8,
        marginTop: 2,
    },
    noteText: {
        color: '#aaa',
        fontSize: 14,
        flex: 1,
        lineHeight: 20,
    },
    actionButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 32,
    },
    shareButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 20,
        flex: 1,
        marginRight: 8,
    },
    shareButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 8,
    },
    historyButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 20,
        flex: 1,
        marginLeft: 8,
        borderWidth: 1,
        borderColor: 'rgba(0,200,150,0.3)',
    },
    historyButtonText: {
        color: GREEN,
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 8,
    },
    modalOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    modalBlur: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    qrModalContent: {
        backgroundColor: CARD_BG,
        borderRadius: 20,
        padding: 20,
        margin: 20,
        width: '90%',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    qrModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        marginBottom: 20,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: BORDER,
    },
    qrModalTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    qrCodeContainer: {
        alignItems: 'center',
        paddingVertical: 20,
    },
    qrCode: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
        ...shadow,
    },
    qrAddressText: {
        color: '#aaa',
        fontSize: 12,
        fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
        textAlign: 'center',
        marginBottom: 20,
        paddingHorizontal: 20,
    },
    qrCopyButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderWidth: 1,
        borderColor: 'rgba(0,200,150,0.3)',
    },
    qrCopyButtonText: {
        color: GREEN,
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 8,
    },
    confirmModalContent: {
        backgroundColor: CARD_BG,
        borderRadius: 20,
        padding: 24,
        margin: 20,
        width: '90%',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    confirmModalHeader: {
        alignItems: 'center',
        marginBottom: 24,
    },
    confirmIconContainer: {
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderRadius: 20,
        padding: 12,
        marginBottom: 16,
    },
    confirmModalTitle: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 12,
        textAlign: 'center',
    },
    confirmModalText: {
        color: '#aaa',
        fontSize: 16,
        textAlign: 'center',
        lineHeight: 24,
    },
    confirmModalButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    cancelButton: {
        backgroundColor: 'rgba(255,77,79,0.1)',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 24,
        flex: 1,
        marginRight: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,77,79,0.3)',
    },
    cancelButtonText: {
        color: RED,
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    confirmButton: {
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 24,
        flex: 1,
        marginLeft: 8,
    },
    confirmButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    successModalContent: {
        backgroundColor: CARD_BG,
        borderRadius: 20,
        padding: 24,
        margin: 20,
        width: '90%',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    successModalHeader: {
        alignItems: 'center',
        marginBottom: 24,
    },
    successIconContainer: {
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderRadius: 24,
        padding: 16,
        marginBottom: 16,
    },
    successModalTitle: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 12,
        textAlign: 'center',
    },
    successModalText: {
        color: '#aaa',
        fontSize: 16,
        textAlign: 'center',
        lineHeight: 24,
    },
    successButton: {
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 32,
        width: '100%',
    },
    successButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
    },
}); 