import { StyleSheet, Platform, Dimensions } from 'react-native';

const BG = '#0A0F1E';
const CARD_BG = '#1A1F2E';
const BORDER = 'rgba(255,255,255,0.06)';
const GREEN = '#00C896';
const RED = '#FF4D4F';

const shadow = Platform.select({
    ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
    },
    android: {
        elevation: 4,
    },
});

const windowHeight = Dimensions.get('window').height;

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: BG,
    },
    container: {
        flex: 1,
        paddingHorizontal: 16,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        paddingTop: 5,
        marginBottom: 8,
    },
    backButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    tradeButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerCenter: {
        flex: 1,
        alignItems: 'center',
    },
    headerTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    notificationButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
    },
    notificationBadge: {
        position: 'absolute',
        top: 8,
        right: 8,
        backgroundColor: RED,
        borderRadius: 10,
        minWidth: 20,
        height: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    notificationBadgeText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
    },
    descriptionBox: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: GREEN,
        ...shadow,
    },
    descriptionIcon: {
        backgroundColor: '#232834',
        borderRadius: 30,
        padding: 12,
        marginRight: 16,
    },
    descriptionContent: {
        flex: 1,
    },
    descriptionTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 4,
    },
    descriptionText: {
        color: '#aaa',
        fontSize: 14,
        lineHeight: 20,
    },
    section: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    sectionTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 12,
    },
    selector: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(35,40,52,0.5)',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
        marginBottom: 12,
    },
    selectorContent: {
        flex: 1,
    },
    selectorText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '500',
    },
    placeholderText: {
        color: '#aaa',
        fontSize: 16,
        fontWeight: '400',
    },
    amountContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(35,40,52,0.5)',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    amountInput: {
        flex: 1,
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        backgroundColor: 'transparent',
    },
    currencyLabel: {
        color: GREEN,
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 12,
    },
    swapContainer: {
        alignItems: 'center',
        marginVertical: 8,
    },
    swapButton: {
        backgroundColor: CARD_BG,
        borderRadius: 20,
        padding: 12,
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    estimatedContainer: {
        backgroundColor: 'rgba(35,40,52,0.5)',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
        alignItems: 'center',
    },
    estimatedLabel: {
        color: '#aaa',
        fontSize: 14,
        marginBottom: 8,
    },
    estimatedAmount: {
        color: '#fff',
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 4,
    },
    estimatedCurrency: {
        color: GREEN,
        fontSize: 16,
        fontWeight: 'bold',
    },
    rateContainer: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    rateHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    rateLabel: {
        color: '#aaa',
        fontSize: 14,
    },
    refreshButton: {
        padding: 4,
    },
    rateValue: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '500',
        marginBottom: 4,
    },
    lastUpdated: {
        color: '#666',
        fontSize: 12,
    },
    convertButtonContainer: {
        marginHorizontal: 16,
        marginBottom: 32,
    },
    convertButton: {
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 16,
        alignItems: 'center',
        justifyContent: 'center',
        ...shadow,
    },
    convertButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    modalOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    modalBlur: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: CARD_BG,
        borderRadius: 20,
        margin: 20,
        width: '90%',
        maxHeight: '80%',
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: BORDER,
    },
    modalTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    modalList: {
        maxHeight: windowHeight * 0.6,
    },
    modalItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: BORDER,
    },
    modalItemContent: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    modalItemName: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '500',
        marginBottom: 2,
    },
    modalItemSubtext: {
        color: '#aaa',
        fontSize: 14,
    },
    modalItemPrice: {
        color: GREEN,
        fontSize: 16,
        fontWeight: 'bold',
    },
    performanceLoading: {
        padding: 40,
        alignItems: 'center',
    },
    loadingText: {
        color: '#aaa',
        fontSize: 16,
    },
    performanceContent: {
        maxHeight: windowHeight * 0.6,
        paddingHorizontal: 20,
    },
    performanceSummary: {
        backgroundColor: 'rgba(35,40,52,0.5)',
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: BORDER,
    },
    performanceRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
    },
    performanceLabel: {
        color: '#aaa',
        fontSize: 14,
        fontWeight: '500',
    },
    performanceValue: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
    priceHistory: {
        backgroundColor: 'rgba(35,40,52,0.5)',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    graphContainer: {
        marginVertical: 16,
        alignItems: 'center',
    },
    graph: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        height: 80,
        width: '100%',
        justifyContent: 'space-between',
        paddingHorizontal: 8,
    },
    graphBarContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'flex-end',
        height: 60,
        marginHorizontal: 1,
    },
    graphBar: {
        width: 4,
        borderRadius: 2,
        minHeight: 2,
    },
    graphLabels: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: 8,
        paddingHorizontal: 8,
    },
    graphLabel: {
        color: '#aaa',
        fontSize: 12,
        fontWeight: '500',
    },
    priceTable: {
        marginTop: 16,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: BORDER,
    },
    priceTableTitle: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 12,
    },
    priceHistoryTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 12,
    },
    priceRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: BORDER,
    },
    priceDate: {
        color: '#aaa',
        fontSize: 14,
    },
    priceValue: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '500',
    },
    performanceError: {
        padding: 40,
        alignItems: 'center',
    },
    errorText: {
        color: RED,
        fontSize: 16,
    },
    noCoinModalContent: {
        backgroundColor: CARD_BG,
        borderRadius: 20,
        padding: 24,
        margin: 20,
        width: '90%',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    noCoinModalHeader: {
        alignItems: 'center',
        marginBottom: 24,
    },
    noCoinIconContainer: {
        backgroundColor: 'rgba(255,77,79,0.1)',
        borderRadius: 20,
        padding: 12,
        marginBottom: 16,
    },
    noCoinModalTitle: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 12,
        textAlign: 'center',
    },
    noCoinModalText: {
        color: '#aaa',
        fontSize: 16,
        textAlign: 'center',
        lineHeight: 24,
    },
    noCoinButton: {
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 32,
        width: '100%',
    },
    noCoinButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
    },
}); 