import { StyleSheet } from 'react-native';

const BG = '#0A0F1E';
const CARD_BG = '#1A1F2E';
const BORDER = 'rgba(255,255,255,0.06)';
const GREEN = '#00C896';

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: BG,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingHorizontal: 20,
        paddingTop: 24,
        marginBottom: 12,
    },
    backButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    contentWrapper: {
        flex: 1,
        width: '100%',
        maxWidth: 500,
        alignSelf: 'center',
        justifyContent: 'flex-start',
    },
    infoCard: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: '5%',
        marginTop: 8,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 18,
        minWidth: 0,
    },
    infoIconCircle: {
        backgroundColor: '#232834',
        borderRadius: 24,
        padding: 12,
        marginRight: 14,
    },
    infoTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 17,
        marginBottom: 2,
        flexShrink: 1,
    },
    infoDesc: {
        color: '#666',
        fontSize: 13,
        flexShrink: 1,
    },
    container: {
        flex: 1,
        paddingHorizontal: 20,
    },
    formContainer: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: BORDER,
    },
    inputContainer: {
        marginBottom: 20,
    },
    inputLabel: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 8,
    },
    textInput: {
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
        color: '#fff',
        fontSize: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    passwordContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: BORDER,
    },
    eyeButton: {
        paddingHorizontal: 16,
        paddingVertical: 14,
    },
    termsContainer: {
        marginBottom: 24,
    },
    checkboxContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    checkbox: {
        width: 20,
        height: 20,
        borderRadius: 4,
        borderWidth: 2,
        borderColor: '#666',
        marginRight: 12,
        marginTop: 2,
        alignItems: 'center',
        justifyContent: 'center',
    },
    checkboxChecked: {
        backgroundColor: GREEN,
        borderColor: GREEN,
    },
    termsText: {
        color: '#aaa',
        fontSize: 14,
        lineHeight: 20,
        flex: 1,
    },
    termsLink: {
        color: GREEN,
        fontWeight: 'bold',
    },
    securityNotice: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderRadius: 12,
        padding: 16,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: 'rgba(0,200,150,0.2)',
    },
    securityText: {
        color: '#aaa',
        fontSize: 14,
        lineHeight: 20,
        marginLeft: 12,
        flex: 1,
    },
    createButton: {
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 16,
        alignItems: 'center',
        marginTop: 8,
    },
    createButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    // Custom Alert Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.7)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    alertContainer: {
        backgroundColor: CARD_BG,
        borderRadius: 20,
        padding: 24,
        alignItems: 'center',
        maxWidth: 320,
        width: '100%',
        borderWidth: 1,
        borderColor: BORDER,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 8,
    },
    alertIconContainer: {
        width: 60,
        height: 60,
        borderRadius: 30,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
    },
    errorIconContainer: {
        backgroundColor: 'rgba(255,107,107,0.1)',
        borderWidth: 2,
        borderColor: 'rgba(255,107,107,0.3)',
    },
    successIconContainer: {
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderWidth: 2,
        borderColor: 'rgba(0,200,150,0.3)',
    },
    alertTitle: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 8,
    },
    alertMessage: {
        color: '#aaa',
        fontSize: 16,
        textAlign: 'center',
        lineHeight: 22,
        marginBottom: 24,
    },
    alertButton: {
        paddingHorizontal: 32,
        paddingVertical: 12,
        borderRadius: 12,
        minWidth: 120,
        alignItems: 'center',
    },
    errorButton: {
        backgroundColor: '#FF6B6B',
    },
    successButton: {
        backgroundColor: GREEN,
    },
    alertButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
}); 