import { StyleSheet, Dimensions } from 'react-native';
import responsiveUtils from '../utils/responsive';

const {
    scale,
    verticalScale,
    horizontalScale,
    fontSize,
    spacing,
    padding,
    borderRadius,
    iconSize,
    buttonSize,
    cardSize,
    getDeviceType,
    isTablet,
    getModalSize,
    getPlatformShadow
} = responsiveUtils;

const BG = '#0A0F1E';
const CARD_BG = '#1A1F2E';
const BORDER = 'rgba(255,255,255,0.06)';
const PILL_BG = '#232834';
const INACTIVE_TAB = '#aaa';
const GREEN = '#00C896';
const RED = '#FF4D4F';

const shadow = getPlatformShadow();
const windowHeight = Dimensions.get('window').height;

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: BG,
    },
    scrollContent: {
        paddingBottom: 32,
        minHeight: '100%',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: horizontalScale(20),
        paddingTop: verticalScale(8),
        paddingBottom: verticalScale(8),
    },
    profileIcon: {
        color: '#fff',
    },
    toggleContainer: {
        flexDirection: 'row',
        backgroundColor: CARD_BG,
        borderRadius: borderRadius.lg,
        padding: scale(2),
    },
    toggleButton: {
        borderRadius: borderRadius.lg - 2,
        paddingHorizontal: horizontalScale(18),
        paddingVertical: verticalScale(6),
        marginRight: scale(2),
    },
    toggleButtonActive: {
        backgroundColor: '#232834',
    },
    toggleButtonInactive: {
        backgroundColor: 'transparent',
    },
    toggleText: {
        fontWeight: 'bold',
        fontSize: fontSize.base,
    },
    toggleTextActive: {
        color: '#fff',
    },
    toggleTextInactive: {
        color: INACTIVE_TAB,
    },
    greenBar: {
        alignSelf: 'center',
        width: scale(16),
        height: scale(2),
        backgroundColor: GREEN,
        marginTop: scale(2),
        borderRadius: scale(1),
    },
    notificationWrapper: {
        position: 'relative',
    },
    notificationIcon: {
        color: '#fff',
    },
    notificationDot: {
        position: 'absolute',
        top: scale(2),
        right: scale(2),
        backgroundColor: RED,
        borderRadius: borderRadius.md,
        width: scale(12),
        height: scale(12),
        borderWidth: scale(2),
        borderColor: BG,
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchBar: {
        backgroundColor: CARD_BG,
        borderRadius: borderRadius.lg,
        marginHorizontal: horizontalScale(16),
        marginBottom: spacing.lg,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: horizontalScale(14),
        height: scale(48),
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    searchText: {
        color: '#aaa',
        fontWeight: 'bold',
        fontSize: fontSize.lg,
        flex: 1,
    },
    onboarding: {
        backgroundColor: CARD_BG,
        borderRadius: borderRadius.lg,
        marginHorizontal: horizontalScale(16),
        marginBottom: spacing.lg,
        flexDirection: 'row',
        alignItems: 'center',
        padding: spacing.lg,
        borderWidth: 1,
        borderColor: BORDER,
    },
    onboardingTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: fontSize.lg,
    },
    onboardingSubtitle: {
        color: '#aaa',
        fontSize: fontSize.sm,
        marginTop: scale(2),
    },
    addFundsButton: {
        backgroundColor: GREEN,
        borderRadius: borderRadius.md,
        paddingHorizontal: horizontalScale(22),
        paddingVertical: verticalScale(10),
        marginLeft: spacing.md,
    },
    addFundsText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: fontSize.base,
    },
    announcements: {
        backgroundColor: CARD_BG,
        borderRadius: borderRadius.lg,
        marginHorizontal: horizontalScale(16),
        marginBottom: spacing.lg + 2,
        padding: spacing.lg,
        borderWidth: 1,
        borderColor: BORDER,
    },
    announcementsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.md - 2,
    },
    announcementsTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: fontSize.lg,
        flex: 1,
    },
    announcementItem: {
        backgroundColor: PILL_BG,
        borderRadius: borderRadius.md,
        flexDirection: 'row',
        alignItems: 'center',
        padding: spacing.md,
        marginBottom: spacing.md - 2,
    },
    announcementIcon: {
        backgroundColor: CARD_BG,
        borderRadius: borderRadius.lg,
        padding: scale(8),
        marginRight: spacing.md,
    },
    announcementMain: {
        flex: 1,
    },
    announcementTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: fontSize.base,
    },
    announcementSubtitle: {
        color: '#aaa',
        fontSize: fontSize.sm,
    },
    announcementTime: {
        color: '#555',
        fontSize: fontSize.xs,
        marginTop: scale(2),
    },
    announcementBadge: {
        backgroundColor: RED,
        borderRadius: borderRadius.md,
        paddingHorizontal: scale(8),
        paddingVertical: scale(2),
        marginLeft: scale(8),
    },
    announcementBadgeText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: fontSize.xs,
    },
    quickActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginHorizontal: horizontalScale(16),
        marginBottom: spacing.lg + 2,
    },
    quickAction: {
        alignItems: 'center',
        flex: 1,
    },
    quickActionIconWrapper: {
        backgroundColor: CARD_BG,
        borderRadius: scale(32),
        padding: spacing.lg,
        marginBottom: scale(6),
        borderWidth: 1,
        borderColor: BORDER,
    },
    quickActionIcon: {
        color: GREEN,
    },
    quickActionLabel: {
        color: '#fff',
        fontSize: fontSize.sm,
        fontWeight: 'bold',
    },
    marketSection: {
        backgroundColor: CARD_BG,
        borderRadius: borderRadius.lg,
        marginHorizontal: horizontalScale(16),
        padding: spacing.lg,
        borderWidth: 1,
        borderColor: BORDER,
    },
    marketTabs: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.md,
    },
    marketTab: {
        marginRight: spacing.md,
        alignItems: 'center',
    },
    marketTabBubble: {
        borderRadius: borderRadius.lg - 2,
        paddingVertical: scale(4),
        paddingHorizontal: spacing.md,
        flexDirection: 'row',
        alignItems: 'center',
        position: 'relative',
    },
    marketTabText: {
        fontWeight: 'bold',
        fontSize: fontSize.base,
    },
    marketTabTextActive: {
        color: '#fff',
    },
    marketTabTextInactive: {
        color: INACTIVE_TAB,
    },
    subTabs: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.md - 2,
    },
    subTab: {
        marginRight: spacing.md - 2,
        alignItems: 'center',
    },
    subTabBubble: {
        borderRadius: borderRadius.lg - 2,
        paddingVertical: scale(3),
        paddingHorizontal: spacing.md + 2,
        flexDirection: 'row',
        alignItems: 'center',
        position: 'relative',
    },
    subTabText: {
        fontWeight: 'bold',
        fontSize: fontSize.sm,
    },
    subTabTextActive: {
        color: '#fff',
    },
    subTabTextInactive: {
        color: INACTIVE_TAB,
    },
    marketHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: scale(6),
    },
    marketHeaderName: {
        color: '#aaa',
        fontSize: fontSize.sm,
        flex: 1,
        textAlign: 'left',
        paddingLeft: scale(8),
    },
    marketHeaderPrice: {
        color: '#aaa',
        fontSize: fontSize.sm,
        flex: 1,
        textAlign: 'center',
    },
    marketHeaderChange: {
        color: '#aaa',
        fontSize: fontSize.sm,
        flex: 1,
        textAlign: 'right',
    },
    marketRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: spacing.md,
    },
    marketName: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: fontSize.base,
        flex: 1,
        textAlign: 'left',
        paddingLeft: scale(8),
    },
    marketPrice: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: fontSize.base,
        flex: 1,
        textAlign: 'center',
    },
    marketChangeWrapper: {
        flex: 1,
        alignItems: 'flex-end',
    },
    marketChange: {
        borderRadius: borderRadius.md,
        paddingHorizontal: scale(10),
        paddingVertical: scale(3),
    },
    marketChangeText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: fontSize.sm,
    },
    modalOverlay: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'flex-end',
        alignItems: 'center',
        zIndex: 100,
        height: '100%',
    },
    modalContentFullWidth: {
        width: '100%',
        height: windowHeight * 0.95,
        backgroundColor: CARD_BG,
        borderRadius: borderRadius.xl,
        padding: spacing.lg + 2,
        borderWidth: 1,
        borderColor: BORDER,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 8,
        alignItems: 'stretch',
        borderTopLeftRadius: borderRadius.xl,
        borderTopRightRadius: borderRadius.xl,
        borderBottomLeftRadius: 0,
        borderBottomRightRadius: 0,
    },
    closeButton: {
        alignSelf: 'flex-end',
        marginBottom: scale(8),
    },
    searchInputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(24,28,35,0.7)',
        borderRadius: borderRadius.lg - 2,
        paddingHorizontal: spacing.md,
        height: scale(44),
        marginBottom: spacing.lg,
        borderWidth: 1,
        borderColor: BORDER,
    },
    resultsSection: {
        flex: 1,
        backgroundColor: 'transparent',
        borderRadius: borderRadius.lg,
        padding: 0,
        borderWidth: 0,
    },
    // Wallet Styles
    walletWelcomeSection: {
        alignItems: 'center',
        paddingHorizontal: horizontalScale(20),
        paddingVertical: verticalScale(32),
        marginBottom: spacing['2xl'],
    },
    walletIconContainer: {
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderRadius: scale(50),
        padding: spacing.xl,
        marginBottom: spacing.xl,
        borderWidth: 1,
        borderColor: 'rgba(0,200,150,0.2)',
    },
    walletWelcomeTitle: {
        color: '#fff',
        fontSize: fontSize['4xl'],
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: spacing.md,
    },
    walletWelcomeSubtitle: {
        color: '#aaa',
        fontSize: fontSize.lg,
        textAlign: 'center',
        lineHeight: verticalScale(24),
        paddingHorizontal: horizontalScale(20),
    },
    createWalletCard: {
        backgroundColor: CARD_BG,
        borderRadius: borderRadius.lg,
        marginHorizontal: horizontalScale(16),
        marginBottom: spacing['2xl'],
        padding: spacing.xl,
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    createWalletHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.md,
    },
    createWalletTitle: {
        color: '#fff',
        fontSize: fontSize['2xl'],
        fontWeight: 'bold',
        marginLeft: spacing.md,
    },
    createWalletDescription: {
        color: '#aaa',
        fontSize: fontSize.base,
        lineHeight: verticalScale(20),
        marginBottom: spacing.xl,
    },
    createWalletButton: {
        backgroundColor: GREEN,
        borderRadius: borderRadius.md,
        paddingVertical: spacing.lg,
        paddingHorizontal: spacing['2xl'],
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    createWalletButtonText: {
        color: '#fff',
        fontSize: fontSize.lg,
        fontWeight: 'bold',
        marginRight: scale(8),
    },
    walletFeaturesSection: {
        paddingHorizontal: horizontalScale(16),
        marginBottom: spacing['2xl'],
    },
    walletFeaturesTitle: {
        color: '#fff',
        fontSize: fontSize['2xl'],
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: spacing.xl,
    },
    walletFeaturesGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    walletFeatureItem: {
        width: isTablet() ? '30%' : '48%',
        backgroundColor: CARD_BG,
        borderRadius: borderRadius.md,
        padding: spacing.lg,
        marginBottom: spacing.md,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: BORDER,
    },
    walletFeatureIcon: {
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderRadius: scale(20),
        padding: spacing.md,
        marginBottom: scale(8),
        borderWidth: 1,
        borderColor: 'rgba(0,200,150,0.2)',
    },
    walletFeatureTitle: {
        color: '#fff',
        fontSize: fontSize.lg,
        fontWeight: 'bold',
        marginBottom: scale(4),
        textAlign: 'center',
    },
    walletFeatureDescription: {
        color: '#aaa',
        fontSize: fontSize.xs,
        textAlign: 'center',
        lineHeight: verticalScale(16),
    },
    // Wallet Transition Animation Styles
    walletTransitionOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: BG,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    walletTransitionContent: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: horizontalScale(40),
        marginTop: verticalScale(-100),
    },
    walletTransitionText: {
        color: '#fff',
        fontSize: fontSize['4xl'],
        fontWeight: 'bold',
        textAlign: 'center',
        marginTop: verticalScale(-20),
    },
}); 