import { StyleSheet, Platform, Dimensions } from 'react-native';

const BG = '#0A0F1E';
const CARD_BG = '#1A1F2E';
const BORDER = 'rgba(255,255,255,0.06)';
const GREEN = '#00C896';
const RED = '#FF4D4F';

const shadow = Platform.select({
    ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
    },
    android: {
        elevation: 4,
    },
});

const windowHeight = Dimensions.get('window').height;

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: BG,
    },
    container: {
        flex: 1,
        paddingHorizontal: 16,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingHorizontal: 20,
        paddingVertical: 16,
        paddingTop: 5,
        marginBottom: 8,
    },
    backButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
    },
    notificationButton: {
        position: 'relative',
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    notificationBadge: {
        position: 'absolute',
        top: -2,
        right: -2,
        backgroundColor: RED,
        borderRadius: 10,
        minWidth: 18,
        height: 18,
        borderWidth: 2,
        borderColor: BG,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 4,
    },
    notificationBadgeText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: 'bold',
    },
    descriptionBox: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: GREEN,
        ...shadow,
    },
    descriptionIcon: {
        backgroundColor: '#232834',
        borderRadius: 30,
        padding: 12,
        marginRight: 16,
    },
    descriptionContent: {
        flex: 1,
    },
    descriptionTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 4,
    },
    descriptionText: {
        color: '#aaa',
        fontSize: 14,
        lineHeight: 20,
    },
    toggleContainer: {
        flexDirection: 'row',
        backgroundColor: '#1A1F2E',
        borderRadius: 16,
        padding: 2,
        marginHorizontal: 16,
        marginBottom: 16,
    },
    toggleButton: {
        borderRadius: 14,
        paddingHorizontal: 18,
        paddingVertical: 6,
        marginRight: 2,
        flex: 1,
        alignItems: 'center',
    },
    toggleButtonActive: {
        backgroundColor: '#232834',
    },
    toggleText: {
        fontWeight: 'bold',
        fontSize: 15,
    },
    toggleTextActive: {
        color: '#fff',
    },
    toggleTextInactive: {
        color: '#aaa',
    },
    greenBar: {
        alignSelf: 'center',
        width: 16,
        height: 2,
        backgroundColor: GREEN,
        marginTop: 2,
        borderRadius: 1,
    },
    continueButtonContainer: {
        marginHorizontal: 16,
        marginBottom: 16,
    },
    continueButton: {
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 16,
        alignItems: 'center',
        justifyContent: 'center',
        ...shadow,
    },
    continueButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    placeholderText: {
        color: '#aaa',
        fontSize: 16,
        fontWeight: 'bold',
    },
    section: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    sectionTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 12,
    },
    coinSelector: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: 'rgba(35,40,52,0.5)',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    coinInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    coinIcon: {
        borderRadius: 12,
        padding: 8,
        marginRight: 12,
    },
    coinDetails: {
        flex: 1,
    },
    coinSymbol: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    coinName: {
        color: '#aaa',
        fontSize: 14,
        marginTop: 2,
    },
    networkSelector: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: 'rgba(35,40,52,0.5)',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    networkInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    networkIcon: {
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderRadius: 10,
        padding: 8,
        marginRight: 12,
    },
    networkDetails: {
        flex: 1,
    },
    networkName: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    networkFee: {
        color: '#aaa',
        fontSize: 14,
        marginTop: 2,
    },
    addressContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(35,40,52,0.5)',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
        marginBottom: 12,
    },
    addressBox: {
        flex: 1,
        marginRight: 12,
    },
    addressText: {
        color: '#fff',
        fontSize: 14,
        fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    },
    copyButton: {
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderRadius: 8,
        padding: 8,
    },
    qrButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: 'rgba(0,200,150,0.3)',
    },
    qrButtonText: {
        color: GREEN,
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 8,
    },
    importantNotes: {
        backgroundColor: 'rgba(255,77,79,0.1)',
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,77,79,0.2)',
    },
    importantTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 12,
    },
    noteItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 8,
    },
    noteBullet: {
        color: RED,
        fontSize: 16,
        marginRight: 8,
        marginTop: 2,
    },
    noteText: {
        color: '#aaa',
        fontSize: 14,
        flex: 1,
        lineHeight: 20,
    },
    actionButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 32,
    },
    shareButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 20,
        flex: 1,
        marginRight: 8,
    },
    shareButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 8,
    },
    historyButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 20,
        flex: 1,
        marginLeft: 8,
        borderWidth: 1,
        borderColor: 'rgba(0,200,150,0.3)',
    },
    historyButtonText: {
        color: GREEN,
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 8,
    },
    modalOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    modalBlur: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: CARD_BG,
        borderRadius: 20,
        padding: 20,
        margin: 20,
        maxHeight: windowHeight * 0.7,
        width: '90%',
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 20,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: BORDER,
    },
    modalTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    coinList: {
        maxHeight: windowHeight * 0.5,
    },
    coinItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 16,
        paddingHorizontal: 12,
        borderRadius: 12,
        marginBottom: 8,
        backgroundColor: 'rgba(35,40,52,0.5)',
    },
    coinItemDetails: {
        flex: 1,
        marginLeft: 12,
    },
    coinItemSymbol: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    coinItemName: {
        color: '#aaa',
        fontSize: 14,
        marginTop: 2,
    },
    networkList: {
        maxHeight: windowHeight * 0.5,
    },
    networkItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 16,
        paddingHorizontal: 12,
        borderRadius: 12,
        marginBottom: 8,
        backgroundColor: 'rgba(35,40,52,0.5)',
    },
    networkItemIcon: {
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderRadius: 10,
        padding: 8,
    },
    networkItemDetails: {
        flex: 1,
        marginLeft: 12,
    },
    networkItemName: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    networkItemFee: {
        color: '#aaa',
        fontSize: 14,
        marginTop: 2,
    },
    networkItemTime: {
        color: '#666',
        fontSize: 12,
        marginTop: 2,
    },
    qrModalContent: {
        backgroundColor: CARD_BG,
        borderRadius: 20,
        padding: 20,
        margin: 20,
        width: '90%',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    qrModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        marginBottom: 20,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: BORDER,
    },
    qrModalTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    qrCodeContainer: {
        alignItems: 'center',
        paddingVertical: 20,
    },
    qrCode: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
        ...shadow,
    },
    qrAddressText: {
        color: '#aaa',
        fontSize: 12,
        fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
        textAlign: 'center',
        marginBottom: 20,
        paddingHorizontal: 20,
    },
    qrCopyButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderWidth: 1,
        borderColor: 'rgba(0,200,150,0.3)',
    },
    qrCopyButtonText: {
        color: GREEN,
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 8,
    },
    mobileMoneySelector: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: 'rgba(35,40,52,0.5)',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    mobileMoneyInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    mobileMoneyDetails: {
        flex: 1,
    },
    mobileMoneyName: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    mobileMoneyList: {
        maxHeight: windowHeight * 0.5,
    },
    mobileMoneyItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 16,
        paddingHorizontal: 12,
        borderRadius: 12,
        marginBottom: 8,
        backgroundColor: 'rgba(35,40,52,0.5)',
    },
    mobileMoneyItemDetails: {
        flex: 1,
    },
    mobileMoneyItemName: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    noMobileMoneyContainer: {
        alignItems: 'center',
        paddingVertical: 24,
        paddingHorizontal: 16,
    },
    noMobileMoneyText: {
        color: '#666',
        fontSize: 16,
        marginTop: 12,
        marginBottom: 16,
        textAlign: 'center',
    },
    connectMobileMoneyButton: {
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    connectMobileMoneyButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
}); 