import { StyleSheet } from 'react-native';

const BG = '#0A0F1E';
const CARD_BG = '#1A1F2E';
const BORDER = 'rgba(255,255,255,0.06)';
const GREEN = '#00C896';
const GRAY = '#aaa';

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: BG,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 24,
        paddingBottom: 8,
    },
    backButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    descriptionBox: {
        backgroundColor: CARD_BG,
        borderRadius: 12,
        marginHorizontal: 16,
        marginBottom: 16,
        paddingVertical: 22,
        paddingHorizontal: 16,
        borderWidth: 1,
        borderColor: GREEN,
        alignItems: 'flex-start',
        minHeight: 70,
    },
    descriptionIconWrapper: {
        backgroundColor: '#232834',
        borderRadius: 16,
        padding: 7,
        marginRight: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    descriptionTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
        marginBottom: 2,
    },
    descriptionText: {
        color: '#aaa',
        fontSize: 13,
    },
    card: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: 16,
        marginBottom: 18,
        padding: 20,
        borderWidth: 1,
        borderColor: BORDER,
    },
    sectionTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 15,
        marginBottom: 10,
    },
    deviceCount: {
        color: GRAY,
        fontWeight: 'bold',
        fontSize: 13,
        marginLeft: 8,
    },
    deviceRow: {
        backgroundColor: '#181C23',
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.06)',
    },
    deviceRowCurrent: {
        borderColor: GREEN,
        backgroundColor: 'rgba(0,200,150,0.08)',
    },
    deviceIconBubble: {
        backgroundColor: '#232834',
        borderRadius: 16,
        padding: 10,
        marginRight: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    deviceName: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 15,
    },
    currentBadge: {
        backgroundColor: GREEN,
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 12,
        borderRadius: 8,
        paddingHorizontal: 8,
        paddingVertical: 2,
        marginLeft: 8,
    },
    deviceLocation: {
        color: GRAY,
        fontSize: 13,
        marginTop: 2,
    },
    deviceLast: {
        color: '#888',
        fontSize: 12,
        marginTop: 2,
    },
    logoutButton: {
        backgroundColor: 'rgba(255,75,75,0.10)',
        borderRadius: 16,
        padding: 8,
        marginLeft: 10,
    },
    tipsText: {
        color: '#aaa',
        fontSize: 13,
        marginBottom: 4,
    },
    popupOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    popupCard: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 28,
        width: '80%',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: BORDER,
    },
    popupTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 20,
        marginBottom: 10,
    },
    popupDesc: {
        color: '#aaa',
        fontSize: 15,
        textAlign: 'center',
    },
    popupButton: {
        backgroundColor: '#232834',
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 25,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        marginTop: 8,
    },
    popupButtonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
}); 