import { StyleSheet } from 'react-native';

const BG = '#0A0F1E';
const CARD_BG = '#1A1F2E';
const BORDER = 'rgba(255,255,255,0.06)';
const GREEN = '#00C896';
const GRAY = '#aaa';

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: BG,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingHorizontal: 20,
        paddingTop: 74,
        marginBottom: 8,
    },
    backButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    descriptionBox: {
        backgroundColor: CARD_BG,
        borderRadius: 12,
        marginHorizontal: 16,
        marginBottom: 16,
        paddingVertical: 22,
        paddingHorizontal: 16,
        borderWidth: 1,
        borderColor: GREEN,
        alignItems: 'flex-start',
        minHeight: 70,
    },
    descriptionIconWrapper: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    descriptionTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
        marginBottom: 2,
    },
    descriptionText: {
        color: '#aaa',
        fontSize: 14,
    },
    card: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: 16,
        marginBottom: 18,
        padding: 20,
        borderWidth: 1,
        borderColor: BORDER,
    },
    sectionTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 15,
        marginBottom: 10,
    },
    sectionDesc: {
        color: '#aaa',
        fontSize: 13,
        marginBottom: 12,
    },
    radioRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#181C23',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 16,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.06)',
    },
    radioRowSelected: {
        borderColor: GREEN,
        backgroundColor: 'rgba(0,200,150,0.08)',
    },
    radioOuter: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: GRAY,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 14,
    },
    radioOuterSelected: {
        borderColor: GREEN,
    },
    radioInner: {
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: GREEN,
    },
    radioText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: 'bold',
    },
    input: {
        backgroundColor: '#181C23',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        color: '#fff',
        fontSize: 15,
        paddingVertical: 12,
        paddingHorizontal: 16,
        marginTop: 10,
        marginBottom: 16,
    },
    inputOther: {
        minHeight: 60,
        fontSize: 17,
        paddingVertical: 16,
    },
    disableButton: {
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: 'center',
    },
    disableButtonText: {
        color: '#181C23',
        fontWeight: 'bold',
        fontSize: 16,
    },
    charCount: {
        color: '#aaa',
        fontSize: 13,
        textAlign: 'right',
        marginTop: 2,
        marginRight: 2,
    },
}); 