import { StyleSheet } from 'react-native';

const BG = '#0A0F1E';
const CARD_BG = '#1A1F2E';
const BORDER = 'rgba(255,255,255,0.06)';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: BG,
        paddingTop: 32,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingHorizontal: 20,
        paddingTop: 35,
        marginBottom: 8,
    },
    backButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    topCard: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: 16,
        marginBottom: 18,
        padding: 18,
        borderWidth: 1,
        borderColor: BORDER,
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconBubble: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 18,
    },
    topCardTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 17,
    },
    topCardDesc: {
        color: '#aaa',
        fontSize: 13,
        marginTop: 2,
    },
    supportCard: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: 16,
        marginBottom: 18,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    supportTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
        marginBottom: 16,
    },
    supportRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
    },
    supportRowTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 15,
    },
    supportRowDesc: {
        color: '#aaa',
        fontSize: 13,
        marginTop: 2,
    },
    faqCard: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: 16,
        marginBottom: 18,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    faqTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
        marginBottom: 16,
    },
    faqRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
    },
    faqQ: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 15,
        flex: 1,
        marginRight: 12,
    },
    faqA: {
        color: '#aaa',
        fontSize: 13,
        lineHeight: 18,
        paddingVertical: 8,
        paddingHorizontal: 4,
    },
    faqDivider: {
        height: 1,
        backgroundColor: BORDER,
        marginVertical: 8,
    },
}); 