import { StyleSheet } from 'react-native';
import responsiveUtils from '../utils/responsive';

const {
    horizontalScale,
    verticalScale,
    scale,
    fontSize,
    spacing,
    padding,
    borderRadius,
    iconSize,
    getContainerMaxWidth,
    isTablet
} = responsiveUtils;

const BG = '#0A0F1E';
const CARD_BG = '#1A1F2E';
const BORDER = 'rgba(255,255,255,0.06)';
const GREEN = '#00C896';

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: BG,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: horizontalScale(20),
        paddingTop: 10,
        marginBottom: spacing.md,
    },
    contentWrapper: {
        flex: 1,
        width: '100%',
        maxWidth: getContainerMaxWidth(),
        alignSelf: 'center',
        justifyContent: 'flex-start',
    },
    backButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    markAllRead: {
        backgroundColor: 'rgba(0,200,150,0.12)',
        paddingHorizontal: horizontalScale(16),
        paddingVertical: verticalScale(8),
        borderRadius: borderRadius.lg,
        borderWidth: 1,
        borderColor: 'rgba(0,200,150,0.2)',
    },
    markAllReadText: {
        color: GREEN,
        fontWeight: '600',
        fontSize: fontSize.sm,
    },
    section: {
        backgroundColor: CARD_BG,
        borderRadius: borderRadius.xl,
        marginHorizontal: isTablet() ? '8%' : '4%',
        marginBottom: spacing.lg,
        padding: spacing.lg + 4,
        borderWidth: 1,
        borderColor: BORDER,
        minWidth: 0,
    },
    sectionTitle: {
        color: '#fff',
        fontWeight: '700',
        fontSize: fontSize.lg + 2,
        marginBottom: spacing.md,
        letterSpacing: 0.5,
    },
    unreadCount: {
        color: GREEN,
        fontWeight: '600',
        fontSize: fontSize.sm,
        opacity: 0.9,
    },
    notificationCard: {
        backgroundColor: 'rgba(26,31,46,0.8)',
        borderRadius: borderRadius.lg,
        flexDirection: 'row',
        alignItems: 'flex-start',
        padding: spacing.lg,
        borderWidth: 0,
        marginTop: scale(8),
        minWidth: 0,
        marginBottom: scale(4),
    },
    notificationIconCircle: {
        backgroundColor: 'rgba(35,40,52,0.8)',
        borderRadius: borderRadius.xl,
        padding: scale(10),
        marginRight: spacing.md,
        marginTop: 2,
    },
    notificationTitle: {
        color: '#fff',
        fontWeight: '600',
        fontSize: fontSize.base + 1,
        flexShrink: 1,
        lineHeight: 20,
        marginBottom: 4,
    },
    notificationDesc: {
        color: '#bbb',
        fontSize: fontSize.sm,
        marginTop: 2,
        flexShrink: 1,
        lineHeight: 18,
        marginBottom: 6,
    },
    notificationTime: {
        color: '#666',
        fontSize: 11,
        marginTop: 2,
        fontWeight: '500',
    },
    greenDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: GREEN,
        marginLeft: 12,
        marginTop: 4,
    },
    infoCard: {
        backgroundColor: CARD_BG,
        borderRadius: 20,
        marginHorizontal: '4%',
        marginTop: 8,
        padding: 20,
        borderWidth: 1,
        borderColor: GREEN,
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 24,
        minWidth: 0,
    },
    infoIconCircle: {
        backgroundColor: 'rgba(35,40,52,0.9)',
        borderRadius: 28,
        padding: 14,
        marginRight: 16,
    },
    infoTitle: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 18,
        marginBottom: 4,
        flexShrink: 1,
        letterSpacing: 0.3,
    },
    infoDesc: {
        color: '#bbb',
        fontSize: 14,
        flexShrink: 1,
        lineHeight: 20,
    },
    caughtUpBox: {
        backgroundColor: 'rgba(26,31,46,0.6)',
        borderRadius: 20,
        marginHorizontal: 16,
        marginTop: 24,
        marginBottom: 16,
        padding: 32,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    caughtUpIconContainer: {
        backgroundColor: 'rgba(35,40,52,0.9)',
        borderRadius: 36,
        padding: 16,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    caughtUpTitle: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 20,
        marginBottom: 10,
        textAlign: 'center',
        letterSpacing: 0.5,
    },
    caughtUpText: {
        color: '#bbb',
        fontSize: 15,
        textAlign: 'center',
        lineHeight: 22,
        fontWeight: '500',
    },
    caughtUpCard: {
        backgroundColor: '#232834',
        borderRadius: 16,
        flexDirection: 'row',
        alignItems: 'center',
        padding: 20,
        marginHorizontal: 16,
        marginBottom: 18,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
    },
    notificationCardUnread: {
        backgroundColor: 'rgba(26,31,46,0.95)',
        borderWidth: 0,
    },
    unreadBar: {
        width: 4,
        height: '80%',
        backgroundColor: GREEN,
        borderRadius: 2,
        marginRight: 14,
        marginTop: 4,
    },
}); 