import { Platform, StyleSheet } from 'react-native';

const BG = '#0A0F1E';
const CARD_BG = '#1A1F2E';
const BORDER = 'rgba(255,255,255,0.06)';
const PILL_BG = '#232834';
const INACTIVE_TAB = '#aaa';
const GREEN = '#00C896';
const RED = '#FF4D4F';

const shadow = Platform.select({
    ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
    },
    android: {
        elevation: 4,
    },
});

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: BG,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingBottom: 16,
        paddingTop: 10,
    },
    headerTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    notificationIcon: {
        color: '#fff',
    },
    notificationDot: {
        position: 'absolute',
        top: 0,
        right: 0,
        backgroundColor: RED,
        borderRadius: 10,
        width: 16,
        height: 16,
        borderWidth: 2,
        borderColor: BG,
        alignItems: 'center',
        justifyContent: 'center',
    },
    descriptionBox: {
        backgroundColor: CARD_BG,
        borderRadius: 12,
        marginHorizontal: 20,
        marginBottom: 20,
        padding: 16,
        borderWidth: 1,
        borderColor: GREEN,
    },
    descriptionContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    descriptionIconContainer: {
        marginRight: 12,
        alignItems: 'center',
        justifyContent: 'center',
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#232834',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
    },
    descriptionIcon: {
        marginRight: 12,
    },
    descriptionText: {
        color: '#aaa',
        fontSize: 14,
        lineHeight: 20,
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 32,
    },
    toggleContainer: {
        flexDirection: 'row',
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: 20,
        marginBottom: 20,
        padding: 2,
        borderWidth: 1,
        borderColor: BORDER,
    },
    toggleButton: {
        flex: 1,
        borderRadius: 14,
        paddingHorizontal: 18,
        paddingVertical: 6,
        marginRight: 2,
        alignItems: 'center',
    },
    toggleButtonActive: {
        backgroundColor: PILL_BG,
    },
    toggleText: {
        color: INACTIVE_TAB,
        fontWeight: 'bold',
        fontSize: 15,
    },
    toggleTextActive: {
        color: '#fff',
    },
    toggleButtonDisabled: {
        backgroundColor: 'rgba(255,77,79,0.1)',
        borderColor: 'rgba(255,77,79,0.3)',
    },
    toggleTextDisabled: {
        color: 'rgba(255,255,255,0.4)',
    },
    greenBar: {
        alignSelf: 'center',
        width: 16,
        height: 2,
        backgroundColor: GREEN,
        marginTop: 2,
        borderRadius: 1,
    },
    selectionContainer: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: 20,
        marginBottom: 20,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    selectionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    selectionLabel: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '500',
    },
    selectionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: PILL_BG,
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    selectionButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '500',
        marginRight: 8,
    },
    dropdownContainer: {
        backgroundColor: CARD_BG,
        borderRadius: 12,
        marginTop: 8,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: BORDER,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 6,
    },
    dropdownItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.03)',
        backgroundColor: 'transparent',
    },
    dropdownItemActive: {
        backgroundColor: 'rgba(0, 200, 150, 0.08)',
        borderLeftWidth: 3,
        borderLeftColor: GREEN,
        borderBottomColor: 'rgba(0, 200, 150, 0.1)',
    },
    dropdownItemText: {
        color: '#ccc',
        fontSize: 15,
        fontWeight: '500',
        letterSpacing: 0.3,
    },
    dropdownItemTextActive: {
        color: '#fff',
        fontWeight: 'bold',
    },
    amountContainer: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: 20,
        marginBottom: 20,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    amountLabel: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '500',
        marginBottom: 12,
    },
    amountInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: PILL_BG,
        borderRadius: 8,
        paddingHorizontal: 12,
    },
    amountInput: {
        flex: 1,
        color: '#fff',
        fontSize: 16,
        paddingVertical: 12,
    },
    amountCurrency: {
        color: '#aaa',
        fontSize: 16,
        fontWeight: '500',
    },
    paymentContainer: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: 20,
        marginBottom: 20,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    sectionTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 12,
    },
    paymentScroll: {
        flexDirection: 'row',
    },
    paymentChip: {
        backgroundColor: PILL_BG,
        borderRadius: 20,
        paddingHorizontal: 16,
        paddingVertical: 8,
        marginRight: 12,
        borderWidth: 1,
        borderColor: BORDER,
    },
    paymentChipActive: {
        backgroundColor: GREEN,
        borderColor: GREEN,
    },
    paymentChipText: {
        color: '#aaa',
        fontSize: 14,
        fontWeight: '500',
    },
    paymentChipTextActive: {
        color: '#fff',
    },
    filtersContainer: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: 20,
        marginBottom: 20,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    filtersHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    filtersContent: {
        marginTop: 12,
    },
    filterRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    filterLabel: {
        color: '#fff',
        fontSize: 14,
        flex: 1,
    },
    filterInputs: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 2,
    },
    filterInput: {
        flex: 1,
        backgroundColor: PILL_BG,
        borderRadius: 6,
        paddingHorizontal: 8,
        paddingVertical: 6,
        color: '#fff',
        fontSize: 14,
        textAlign: 'center',
    },
    filterSeparator: {
        color: '#aaa',
        marginHorizontal: 8,
    },
    ordersContainer: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: 20,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    ordersHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    sortButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: PILL_BG,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 6,
    },
    sortButtonText: {
        color: '#aaa',
        fontSize: 14,
        marginLeft: 6,
    },
    orderCard: {
        backgroundColor: PILL_BG,
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: BORDER,
    },
    orderHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    userInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    userAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: GREEN,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    userInitial: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    userDetails: {
        flex: 1,
    },
    userName: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 4,
    },
    userStats: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    userRating: {
        color: '#aaa',
        fontSize: 12,
        marginRight: 12,
    },
    userOrders: {
        color: '#aaa',
        fontSize: 12,
    },
    orderStatus: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    onlineIndicator: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: GREEN,
        marginRight: 6,
    },
    onlineText: {
        color: '#aaa',
        fontSize: 12,
    },
    orderDetails: {
        marginBottom: 12,
    },
    orderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 6,
    },
    orderLabel: {
        color: '#aaa',
        fontSize: 14,
    },
    orderValue: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '500',
    },
    orderActions: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    chatButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 8,
    },
    chatButtonText: {
        color: '#aaa',
        fontSize: 14,
        marginLeft: 6,
    },
    actionButton: {
        borderRadius: 8,
        paddingHorizontal: 24,
        paddingVertical: 10,
        minWidth: 80,
        alignItems: 'center',
    },
    buyButton: {
        backgroundColor: GREEN,
    },
    sellButton: {
        backgroundColor: '#FF6B6B',
    },
    actionButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
    // Modal Styles
    modalOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    modalBlur: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: CARD_BG,
        borderRadius: 20,
        padding: 24,
        margin: 20,
        width: '90%',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    modalIcon: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: 'rgba(255,77,79,0.1)',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 12,
        textAlign: 'center',
    },
    modalText: {
        color: '#aaa',
        fontSize: 16,
        textAlign: 'center',
        lineHeight: 24,
        marginBottom: 24,
    },
    modalButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    modalButtonSecondary: {
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 24,
        flex: 1,
        marginRight: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    modalButtonSecondaryText: {
        color: '#aaa',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    modalButtonPrimary: {
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 24,
        flex: 1,
        marginLeft: 8,
    },
    modalButtonPrimaryText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
    },
}); 