import { Platform, StyleSheet } from 'react-native';

const BG = '#0A0F1E';
const CARD_BG = '#1A1F2E';
const BORDER = 'rgba(255,255,255,0.06)';
const PILL_BG = '#232834';
const GREEN = '#00C896';

const shadow = Platform.select({
    ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
    },
    android: {
        elevation: 4,
    },
});

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: BG,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingBottom: 16,
        paddingTop: 10,
    },
    headerTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    descriptionBox: {
        backgroundColor: CARD_BG,
        borderRadius: 12,
        marginHorizontal: 20,
        marginBottom: 20,
        padding: 16,
        borderWidth: 1,
        borderColor: GREEN,
    },
    descriptionContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    descriptionIconContainer: {
        marginRight: 12,
        alignItems: 'center',
        justifyContent: 'center',
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#232834',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
    },
    descriptionText: {
        color: '#aaa',
        fontSize: 14,
        lineHeight: 20,
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 32,
    },
    traderCard: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: 20,
        marginBottom: 24,
        padding: 20,
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    traderHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    traderAvatar: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: GREEN,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
    },
    traderInitial: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
    },
    traderInfo: {
        flex: 1,
    },
    traderName: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 4,
    },
    traderStatus: {
        color: GREEN,
        fontSize: 14,
        fontWeight: '500',
    },
    traderDetails: {
        backgroundColor: PILL_BG,
        borderRadius: 12,
        padding: 16,
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    detailLabel: {
        color: '#aaa',
        fontSize: 14,
    },
    detailValue: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    buyButton: {
        backgroundColor: GREEN,
        borderRadius: 12,
        marginHorizontal: 20,
        paddingVertical: 16,
        alignItems: 'center',
        ...shadow,
    },
    buyButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    inputBox: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: 20,
        marginBottom: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    inputLabel: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 12,
    },
    amountInputBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: PILL_BG,
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    currencySymbol: {
        color: '#aaa',
        fontSize: 18,
        fontWeight: '600',
        marginRight: 8,
    },
    amountInputField: {
        flex: 1,
        color: '#fff',
        fontSize: 18,
        fontWeight: '600',
    },
    calculationDisplay: {
        backgroundColor: PILL_BG,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginTop: 12,
    },
    calculationText: {
        color: '#aaa',
        fontSize: 14,
    },
    calculationValue: {
        color: GREEN,
        fontSize: 14,
        fontWeight: 'bold',
    },
    limitHint: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 165, 0, 0.1)',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginTop: 12,
    },
    limitHintText: {
        color: '#FFA500',
        fontSize: 12,
        marginLeft: 6,
    },
    paymentMethodBox: {
        gap: 12,
    },
    paymentMethodOption: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: PILL_BG,
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    paymentMethodOptionActive: {
        backgroundColor: 'rgba(0, 200, 150, 0.1)',
        borderColor: GREEN,
    },
    paymentMethodContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    paymentMethodText: {
        color: '#ccc',
        fontSize: 16,
        fontWeight: '500',
        marginLeft: 12,
    },
    paymentMethodTextActive: {
        color: '#fff',
        fontWeight: 'bold',
    },
    modalOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    blurView: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    simpleOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.7)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: CARD_BG,
        borderRadius: 20,
        marginHorizontal: 20,
        width: '90%',
        maxWidth: 400,
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: BORDER,
    },
    modalTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    closeButton: {
        padding: 4,
    },
    modalBody: {
        padding: 20,
    },
    modalLabel: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 16,
    },
    amountInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: PILL_BG,
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    limitInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 165, 0, 0.1)',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
    },
    limitText: {
        color: '#FFA500',
        fontSize: 12,
        marginLeft: 6,
    },
    paymentOption: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: PILL_BG,
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: BORDER,
    },
    paymentOptionActive: {
        backgroundColor: 'rgba(0, 200, 150, 0.1)',
        borderColor: GREEN,
    },
    paymentOptionContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    paymentOptionText: {
        color: '#ccc',
        fontSize: 16,
        fontWeight: '500',
        marginLeft: 12,
    },
    paymentOptionTextActive: {
        color: '#fff',
        fontWeight: 'bold',
    },
    confirmationCard: {
        backgroundColor: PILL_BG,
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
    },
    confirmationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    confirmationLabel: {
        color: '#aaa',
        fontSize: 14,
    },
    confirmationValue: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    warningBox: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: 'rgba(255, 165, 0, 0.1)',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 12,
    },
    warningText: {
        color: '#FFA500',
        fontSize: 13,
        marginLeft: 8,
        flex: 1,
        lineHeight: 18,
    },
    modalFooter: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        paddingBottom: 20,
        gap: 12,
    },
    cancelButton: {
        flex: 1,
        backgroundColor: PILL_BG,
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: BORDER,
    },
    cancelButtonText: {
        color: '#aaa',
        fontSize: 16,
        fontWeight: '600',
    },
    confirmButton: {
        flex: 1,
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: 'center',
    },
    confirmButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    successIcon: {
        alignSelf: 'center',
        marginBottom: 16,
    },
    successMessage: {
        color: '#fff',
        fontSize: 16,
        textAlign: 'center',
        marginBottom: 8,
        lineHeight: 22,
    },
}); 