import { Platform, StyleSheet } from 'react-native';

const BG = '#0A0F1E';
const CARD_BG = '#1A1F2E';
const BORDER = 'rgba(255,255,255,0.06)';
const GREEN = '#00C896';
const RED = '#FF6B6B';

const shadow = Platform.select({
    ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
    },
    android: {
        elevation: 4,
    },
});

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: BG,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingBottom: 16,
        paddingTop: 10,
    },
    descriptionBox: {
        backgroundColor: CARD_BG,
        borderRadius: 12,
        marginHorizontal: 20,
        marginBottom: 20,
        padding: 16,
        borderWidth: 1,
        borderColor: GREEN,
        ...shadow,
    },
    descriptionContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    descriptionIconContainer: {
        marginRight: 12,
        alignItems: 'center',
        justifyContent: 'center',
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#232834',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
    },
    descriptionText: {
        color: '#aaa',
        fontSize: 14,
        lineHeight: 20,
        flex: 1,
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 32,
    },
    traderCard: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    traderHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    traderAvatar: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: RED,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    traderInitial: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    traderInfo: {
        flex: 1,
    },
    traderName: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 4,
    },
    traderStatus: {
        color: '#aaa',
        fontSize: 12,
    },
    traderDetails: {
        borderTopWidth: 1,
        borderTopColor: BORDER,
        paddingTop: 16,
    },
    detailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    detailLabel: {
        color: '#aaa',
        fontSize: 14,
    },
    detailValue: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '500',
    },
    inputBox: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    inputLabel: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 12,
    },
    amountInputBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: BG,
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: BORDER,
    },
    currencySymbol: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginRight: 8,
    },
    amountInputField: {
        flex: 1,
        color: '#fff',
        fontSize: 16,
        fontWeight: '500',
    },
    calculationDisplay: {
        marginTop: 12,
        padding: 12,
        backgroundColor: 'rgba(255,107,107,0.1)',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,107,107,0.2)',
    },
    calculationText: {
        color: '#aaa',
        fontSize: 14,
    },
    calculationValue: {
        color: RED,
        fontWeight: '600',
    },
    limitHint: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 12,
        padding: 8,
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderRadius: 6,
    },
    limitHintText: {
        color: '#aaa',
        fontSize: 12,
        marginLeft: 6,
    },
    paymentMethodBox: {
        gap: 12,
    },
    paymentMethodOption: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        backgroundColor: BG,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: BORDER,
    },
    paymentMethodOptionActive: {
        borderColor: RED,
        backgroundColor: 'rgba(255,107,107,0.1)',
    },
    paymentMethodContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    paymentMethodText: {
        color: '#aaa',
        fontSize: 14,
        marginLeft: 12,
    },
    paymentMethodTextActive: {
        color: RED,
        fontWeight: '600',
    },
    sellButton: {
        backgroundColor: RED,
        borderRadius: 16,
        paddingVertical: 16,
        alignItems: 'center',
        marginTop: 20,
        ...shadow,
    },
    sellButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    modalOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    simpleOverlay: {
        backgroundColor: 'rgba(0,0,0,0.5)',
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: CARD_BG,
        borderRadius: 20,
        padding: 24,
        margin: 20,
        maxWidth: 400,
        width: '100%',
        borderWidth: 1,
        borderColor: BORDER,
        ...shadow,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '600',
    },
    closeButton: {
        padding: 4,
    },
    modalBody: {
        marginBottom: 20,
    },
    modalLabel: {
        color: '#aaa',
        fontSize: 14,
        marginBottom: 8,
    },
    confirmationCard: {
        backgroundColor: BG,
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
    },
    confirmationRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    confirmationLabel: {
        color: '#aaa',
        fontSize: 14,
    },
    confirmationValue: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '500',
    },
    warningBox: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: 'rgba(255,165,0,0.1)',
        borderRadius: 8,
        padding: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,165,0,0.2)',
    },
    warningText: {
        color: '#FFA500',
        fontSize: 12,
        marginLeft: 8,
        flex: 1,
        lineHeight: 16,
    },
    modalFooter: {
        flexDirection: 'row',
        gap: 12,
    },
    cancelButton: {
        flex: 1,
        backgroundColor: BG,
        borderRadius: 12,
        paddingVertical: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: BORDER,
    },
    cancelButtonText: {
        color: '#aaa',
        fontSize: 14,
        fontWeight: '500',
    },
    confirmButton: {
        flex: 1,
        backgroundColor: RED,
        borderRadius: 12,
        paddingVertical: 12,
        alignItems: 'center',
    },
    confirmButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    successIcon: {
        alignSelf: 'center',
        marginBottom: 16,
    },
    successMessage: {
        color: '#fff',
        fontSize: 14,
        textAlign: 'center',
        marginBottom: 8,
    },
}); 