import { StyleSheet } from 'react-native';

const BG = '#0A0F1E';
const CARD_BG = '#1A1F2E';
const BORDER = 'rgba(255,255,255,0.06)';
const GREEN = '#00C896';
const INACTIVE_TAB = '#aaa';

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: BG,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        marginBottom: 8,
        paddingTop: 24,
    },
    backButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    descriptionBox: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: 16,
        marginBottom: 18,
        padding: 20,
        borderWidth: 1,
        borderColor: GREEN,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    iconBubble: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    descriptionTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 18,
        marginBottom: 4,
    },
    descriptionText: {
        color: '#aaa',
        fontSize: 14,
        lineHeight: 18,
    },
    pillToggleContainer: {
        flexDirection: 'row',
        backgroundColor: CARD_BG,
        borderRadius: 16,
        alignSelf: 'center',
        marginBottom: 18,
        padding: 2,
    },
    pillToggleButton: {
        borderRadius: 14,
        paddingHorizontal: 18,
        paddingVertical: 6,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
    },
    pillToggleButtonActive: {
        backgroundColor: '#232834',
    },
    pillToggleButtonInactive: {
        backgroundColor: 'transparent',
    },
    pillToggleText: {
        fontWeight: 'bold',
        fontSize: 15,
    },
    pillToggleTextActive: {
        color: '#fff',
    },
    pillToggleTextInactive: {
        color: INACTIVE_TAB,
    },
    pillToggleUnderline: {
        alignSelf: 'center',
        width: 16,
        height: 2,
        backgroundColor: GREEN,
        marginTop: 2,
        borderRadius: 1,
    },
    pillToggleContainerDashboard: {
        flexDirection: 'row',
        backgroundColor: CARD_BG,
        borderRadius: 16,
        alignSelf: 'center',
        marginBottom: 18,
        padding: 2,
    },
    pillToggleButtonDashboard: {
        borderRadius: 14,
        paddingHorizontal: 18,
        paddingVertical: 6,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
    },
    pillToggleButtonActiveDashboard: {
        backgroundColor: '#232834',
    },
    pillToggleButtonInactiveDashboard: {
        backgroundColor: 'transparent',
    },
    pillToggleTextDashboard: {
        fontWeight: 'bold',
        fontSize: 15,
    },
    pillToggleTextActiveDashboard: {
        color: '#fff',
    },
    pillToggleTextInactiveDashboard: {
        color: INACTIVE_TAB,
    },
    pillToggleUnderlineDashboard: {
        alignSelf: 'center',
        width: 16,
        height: 2,
        backgroundColor: GREEN,
        marginTop: 2,
        borderRadius: 1,
    },
    infoCard: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: 16,
        marginBottom: 18,
        padding: 20,
        borderWidth: 1,
        borderColor: BORDER,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    infoCardTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
        marginBottom: 16,
    },
    bankRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        backgroundColor: 'rgba(255,255,255,0.02)',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.04)',
    },
    bankName: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
        marginBottom: 2,
    },
    bankDesc: {
        color: INACTIVE_TAB,
        fontSize: 14,
    },
    connectedBadge: {
        backgroundColor: GREEN,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 6,
        alignSelf: 'center',
        marginLeft: 12,
        shadowColor: GREEN,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    connectedText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 11,
        letterSpacing: 0.5,
    },
    popupOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    popupCard: {
        backgroundColor: CARD_BG,
        borderRadius: 20,
        padding: 28,
        width: '85%',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: BORDER,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 16,
        elevation: 12,
    },
    popupIconCircle: {
        backgroundColor: 'rgba(0,200,150,0.15)',
        borderRadius: 50,
        width: 80,
        height: 80,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
        borderWidth: 1,
        borderColor: 'rgba(0,200,150,0.3)',
    },
    popupTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 22,
        marginBottom: 8,
        textAlign: 'center',
    },
    popupSubtitle: {
        color: '#aaa',
        fontSize: 15,
        marginBottom: 24,
        textAlign: 'center',
        lineHeight: 20,
    },
    popupButtonContainer: {
        flexDirection: 'row',
        gap: 12,
        width: '100%',
    },
    popupButtonSecondary: {
        backgroundColor: 'rgba(255,255,255,0.08)',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 24,
        flex: 1,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.12)',
    },
    popupButtonPrimary: {
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 24,
        flex: 1,
        alignItems: 'center',
        shadowColor: GREEN,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    popupButtonTextSecondary: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    popupButtonTextPrimary: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    popupButtonPrimaryDisabled: {
        backgroundColor: '#666',
        shadowOpacity: 0,
        elevation: 0,
    },
    inputContainer: {
        width: '100%',
        marginBottom: 24,
    },
    inputLabel: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 8,
    },
    textInput: {
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
        color: '#fff',
        fontSize: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    inputHint: {
        color: '#666',
        fontSize: 12,
        marginTop: 4,
        textAlign: 'right',
    },
    textInputError: {
        borderColor: '#ff4444',
        backgroundColor: 'rgba(255,68,68,0.05)',
    },
    errorText: {
        color: '#ff4444',
        fontSize: 12,
        marginTop: 4,
        fontWeight: '500',
    },

}); 