import { StyleSheet } from 'react-native';

const BG = '#0A0F1E';
const CARD_BG = '#1A1F2E';
const BORDER = 'rgba(255,255,255,0.06)';
const GREEN = '#00C896';
const INACTIVE_TAB = '#aaa';

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: BG,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        marginBottom: 8,
        paddingTop: 24,
    },
    backButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    settingsButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 10,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    profileInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: 16,
        marginBottom: 18,
    },
    profilePicWrapper: {
        backgroundColor: '#232834',
        borderRadius: 40,
        width: 80,
        height: 80,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.08)',
    },
    profilePicImageWrapper: {
        width: 54,
        height: 54,
        borderRadius: 27,
        overflow: 'hidden',
        alignItems: 'center',
        justifyContent: 'center',
    },
    profilePicImage: {
        width: 54,
        height: 54,
        borderRadius: 27,
        resizeMode: 'cover',
    },
    defaultAvatarContainer: {
        width: 54,
        height: 54,
        borderRadius: 27,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    defaultAvatarText: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    cameraIconOverlay: {
        position: 'absolute',
        bottom: -2,
        right: -2,
        backgroundColor: GREEN,
        borderRadius: 12,
        width: 24,
        height: 24,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: BG,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    profileInfo: {
        flex: 1,
    },
    profileName: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 18,
        marginBottom: 4,
    },
    profileEmail: {
        color: '#aaa',
        fontSize: 14,
    },
    editButton: {
        backgroundColor: 'rgba(0,200,150,0.08)',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 6,
    },
    editButtonText: {
        color: GREEN,
        fontWeight: 'bold',
        fontSize: 13,
    },
    profileNameInput: {
        borderBottomWidth: 1,
        borderBottomColor: BORDER,
        paddingVertical: 2,
        marginBottom: -2,
        minWidth: 100,
    },
    section: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: 16,
        marginBottom: 18,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    sectionTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
        marginBottom: 12,
    },
    sectionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: BORDER,
    },
    sectionRowLast: {
        borderBottomWidth: 0,
    },
    sectionRowTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 15,
    },
    sectionRowDesc: {
        color: '#aaa',
        fontSize: 13,
    },
    pillToggleContainer: {
        flexDirection: 'row',
        backgroundColor: CARD_BG,
        borderRadius: 16,
        alignSelf: 'center',
        marginBottom: 18,
        padding: 2,
    },
    pillToggleButton: {
        borderRadius: 14,
        paddingHorizontal: 18,
        paddingVertical: 6,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
    },
    pillToggleButtonActive: {
        backgroundColor: '#232834',
    },
    pillToggleButtonInactive: {
        backgroundColor: 'transparent',
    },
    pillToggleText: {
        fontWeight: 'bold',
        fontSize: 15,
    },
    pillToggleTextActive: {
        color: '#fff',
    },
    pillToggleTextInactive: {
        color: INACTIVE_TAB,
    },
    pillToggleUnderline: {
        alignSelf: 'center',
        width: 16,
        height: 2,
        backgroundColor: GREEN,
        marginTop: 2,
        borderRadius: 1,
    },
    profileInfoCentered: {
        alignItems: 'center',
        marginHorizontal: 16,
        marginBottom: 18,
    },
    popupOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(16,20,28,0.3)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 100,
    },
    popupCard: {
        backgroundColor: '#232834',
        borderRadius: 16,
        padding: 28,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
    },
    popupTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 17,
        marginBottom: 18,
    },
    popupButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0,200,150,0.08)',
        borderRadius: 10,
        paddingVertical: 12,
        paddingHorizontal: 22,
        marginBottom: 12,
    },
    popupButtonText: {
        color: GREEN,
        fontWeight: 'bold',
        fontSize: 16,
    },
    iconBubble: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 10,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
    },
    securityRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
    },
    securityRowTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 15,
    },
    securityRowDesc: {
        color: '#aaa',
        fontSize: 13,
    },
    popupText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
        textAlign: 'center',
    },
}); 