import { StyleSheet } from 'react-native';

const BG = '#0A0F1E';
const CARD_BG = '#1A1F2E';
const BORDER = 'rgba(255,255,255,0.06)';
const GREEN = '#00C896';
const INACTIVE_TAB = '#aaa';

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: BG,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingTop: 24,
        paddingBottom: 8,
    },
    backButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: BORDER,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
        flex: 1,
        textAlign: 'center',
    },
    headerRight: {
        width: 54,
    },
    scrollContent: {
        paddingBottom: 32,
        minHeight: '100%',
    },
    descriptionBox: {
        backgroundColor: CARD_BG,
        borderRadius: 12,
        marginHorizontal: 16,
        marginBottom: 16,
        paddingVertical: 22,
        paddingHorizontal: 16,
        borderWidth: 1,
        borderColor: GREEN,
        alignItems: 'flex-start',
        minHeight: 70,
    },
    descriptionIcon: {
        backgroundColor: '#232834',
        borderRadius: 16,
        padding: 7,
        marginRight: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    descriptionTextContainer: {
        flex: 1,
        minWidth: 0,
    },
    descriptionTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
        marginBottom: 2,
    },
    descriptionText: {
        color: INACTIVE_TAB,
        fontSize: 13,
    },
    sectionCard: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        marginHorizontal: 16,
        marginBottom: 18,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    sectionTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
        marginBottom: 12,
    },
    amountContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    currencySelector: {
        marginRight: 12,
    },
    currencyButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#232834',
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderWidth: 1,
        borderColor: BORDER,
    },

    currencySymbol: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 14,
        marginRight: 6,
    },
    amountInputContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#232834',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: BORDER,
    },
    amountInput: {
        flex: 1,
        color: '#fff',
        fontSize: 18,
        fontWeight: '600',
    },
    currencyLabel: {
        color: INACTIVE_TAB,
        fontSize: 14,
        marginLeft: 8,
    },
    balanceInfo: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: BORDER,
    },
    balanceLabel: {
        color: INACTIVE_TAB,
        fontSize: 13,
    },
    balanceAmount: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '600',
    },
    receiverInput: {
        backgroundColor: '#232834',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: BORDER,
        color: '#fff',
        fontSize: 14,
        marginBottom: 12,
    },
    receiverInfo: {
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    receiverInfoText: {
        color: INACTIVE_TAB,
        fontSize: 12,
        marginLeft: 6,
        flex: 1,
        lineHeight: 16,
    },
    feeContainer: {
        gap: 8,
    },
    feeRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    feeLabel: {
        color: INACTIVE_TAB,
        fontSize: 13,
    },
    feeAmount: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '600',
    },
    totalAmount: {
        color: GREEN,
        fontSize: 14,
        fontWeight: 'bold',
    },
    buttonContainer: {
        paddingHorizontal: 16,
        marginTop: 8,
    },
    sendButton: {
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 16,
        paddingHorizontal: 24,
        alignItems: 'center',
        justifyContent: 'center',
    },
    disabledButton: {
        backgroundColor: '#2A2F3E',
        opacity: 0.5,
    },
    sendButtonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    modalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: '#232834',
        borderRadius: 20,
        padding: 24,
        width: 340,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 8,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: BORDER,
    },
    modalHeaderContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    modalHeaderIcon: {
        backgroundColor: 'rgba(0, 200, 150, 0.1)',
        borderRadius: 12,
        padding: 8,
        marginRight: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 18,
    },
    closeButton: {
        backgroundColor: '#2A2F3E',
        borderRadius: 20,
        padding: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    currencyList: {
        gap: 8,
    },
    currencyOption: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 16,
        paddingHorizontal: 16,
        borderRadius: 12,
        backgroundColor: '#2A2F3E',
        borderWidth: 1,
        borderColor: 'transparent',
    },
    selectedCurrencyOption: {
        backgroundColor: 'rgba(0, 200, 150, 0.1)',
        borderColor: GREEN,
    },
    currencyOptionContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },

    currencyOptionText: {
        flex: 1,
    },
    currencyOptionSymbol: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
        marginBottom: 2,
    },
    selectedCurrencySymbol: {
        color: GREEN,
    },
    currencyOptionName: {
        color: INACTIVE_TAB,
        fontSize: 13,
    },
    checkmarkContainer: {
        backgroundColor: 'rgba(0, 200, 150, 0.1)',
        borderRadius: 12,
        padding: 6,
        alignItems: 'center',
        justifyContent: 'center',
    },
    confirmationContent: {
        marginBottom: 24,
    },
    confirmationText: {
        color: '#fff',
        fontSize: 16,
        textAlign: 'center',
        marginBottom: 12,
    },
    receiverAddress: {
        color: GREEN,
        fontSize: 14,
        textAlign: 'center',
        marginBottom: 20,
        fontWeight: '600',
    },
    transactionDetails: {
        backgroundColor: '#2A2F3E',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
    },
    detailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    detailLabel: {
        color: INACTIVE_TAB,
        fontSize: 14,
    },
    detailValue: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    modalButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    cancelButton: {
        flex: 1,
        backgroundColor: '#2A2F3E',
        borderRadius: 12,
        paddingVertical: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: BORDER,
    },
    cancelButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
    },
    confirmButton: {
        flex: 1,
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 12,
        alignItems: 'center',
    },
    confirmButtonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    successIconContainer: {
        alignItems: 'center',
        marginBottom: 16,
    },
    successTitle: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 22,
        textAlign: 'center',
        marginBottom: 12,
    },
    successText: {
        color: INACTIVE_TAB,
        fontSize: 16,
        textAlign: 'center',
        marginBottom: 24,
        lineHeight: 22,
    },
    successButton: {
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 32,
        alignItems: 'center',
    },
    successButtonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
}); 