import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#0A0F1E',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 24,
    },
    backButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 12,
    },
    menuButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '600',
    },
    pairSelector: {
        paddingHorizontal: 20,
        paddingVertical: 16,
    },
    pairButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#1A1F2E',
        borderRadius: 20,
        padding: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 6,
    },
    pairInfo: {
        flex: 1,
    },
    pairSymbol: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '600',
        marginBottom: 2,
    },
    pairName: {
        color: '#CCCCCC',
        fontSize: 14,
    },
    pairPrice: {
        alignItems: 'flex-end',
        marginRight: 12,
    },
    priceText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 2,
    },
    changeText: {
        fontSize: 14,
        fontWeight: '500',
    },
    toggleSection: {
        paddingHorizontal: 20,
        marginBottom: 20,
    },
    toggleContainer: {
        flexDirection: 'row',
        backgroundColor: '#1A1F2E',
        borderRadius: 16,
        padding: 2,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.06)',
    },
    toggleButton: {
        flex: 1,
        borderRadius: 14,
        paddingHorizontal: 18,
        paddingVertical: 6,
        alignItems: 'center',
    },
    buyToggleButton: {
        backgroundColor: '#232834',
    },
    sellToggleButton: {
        backgroundColor: '#232834',
    },
    toggleText: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#aaa',
    },
    buyToggleText: {
        color: '#fff',
    },
    sellToggleText: {
        color: '#fff',
    },
    activeIndicator: {
        alignSelf: 'center',
        width: 16,
        height: 2,
        backgroundColor: '#00C896',
        marginTop: 2,
        borderRadius: 1,
    },
    scrollContainer: {
        flex: 1,
    },
    formSection: {
        paddingHorizontal: 20,
        marginBottom: 20,
    },
    sectionLabel: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 12,
    },
    orderTypeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#232834',
        borderRadius: 20,
        padding: 18,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 6,
    },
    orderTypeText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '500',
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#232834',
        borderRadius: 20,
        paddingHorizontal: 18,
        paddingVertical: 16,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 6,
    },
    inputField: {
        flex: 1,
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '500',
    },
    inputSuffix: {
        color: '#CCCCCC',
        fontSize: 16,
        fontWeight: '500',
        marginLeft: 8,
    },
    amountOptions: {
        flexDirection: 'row',
        marginTop: 12,
        gap: 8,
    },
    amountOption: {
        flex: 1,
        backgroundColor: '#232834',
        borderRadius: 16,
        paddingVertical: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    amountOptionText: {
        color: '#CCCCCC',
        fontSize: 14,
        fontWeight: '500',
    },
    totalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#232834',
        borderRadius: 20,
        padding: 18,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 6,
    },
    totalLabel: {
        color: '#CCCCCC',
        fontSize: 16,
        fontWeight: '500',
    },
    totalValue: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    balanceRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#232834',
        borderRadius: 20,
        padding: 18,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 6,
    },
    balanceLabel: {
        color: '#CCCCCC',
        fontSize: 16,
        fontWeight: '500',
    },
    balanceValue: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    placeOrderButton: {
        marginHorizontal: 20,
        marginBottom: 20,
        borderRadius: 20,
        paddingVertical: 18,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.25,
        shadowRadius: 16,
        elevation: 8,
    },
    buyButton: {
        backgroundColor: '#00C896',
        borderWidth: 1,
        borderColor: '#00C896',
    },
    sellButton: {
        backgroundColor: '#FF4D4F',
        borderWidth: 1,
        borderColor: '#FF4D4F',
    },
    placeOrderText: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '600',
    },
    marketInfoSection: {
        paddingHorizontal: 20,
        marginBottom: 20,
    },
    marketInfoTitle: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '600',
        marginBottom: 16,
    },
    marketInfoGrid: {
        backgroundColor: '#1A1F2E',
        borderRadius: 20,
        padding: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 6,
    },
    marketInfoItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
    },
    marketInfoLabel: {
        color: '#CCCCCC',
        fontSize: 14,
        fontWeight: '500',
    },
    marketInfoValue: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '600',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalBlur: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: '#181E2A',
        borderRadius: 20,
        padding: 24,
        marginHorizontal: 20,
        width: width - 40,
        maxHeight: height * 0.7,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 16,
        elevation: 10,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.08)',
    },
    modalTitle: {
        color: '#FFFFFF',
        fontSize: 20,
        fontWeight: 'bold',
    },
    modalScroll: {
        maxHeight: 400,
    },
    pairOption: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 18,
        paddingHorizontal: 18,
        borderRadius: 16,
        marginBottom: 10,
        backgroundColor: '#232834',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    pairOptionSelected: {
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderColor: 'rgba(0,200,150,0.3)',
    },
    pairOptionInfo: {
        flex: 1,
    },
    pairOptionSymbol: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 2,
    },
    pairOptionName: {
        color: '#CCCCCC',
        fontSize: 14,
    },
    pairOptionPrice: {
        alignItems: 'flex-end',
    },
    pairOptionPriceText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 2,
    },
    pairOptionChange: {
        fontSize: 14,
        fontWeight: '500',
    },
    orderTypeOption: {
        paddingVertical: 18,
        paddingHorizontal: 18,
        borderRadius: 16,
        marginBottom: 10,
        backgroundColor: '#232834',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    orderTypeOptionSelected: {
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderColor: 'rgba(0,200,150,0.3)',
    },
    orderTypeOptionText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '500',
    },
    orderTypeOptionTextSelected: {
        color: '#00C896',
        fontWeight: '600',
    },
}); 