import { StyleSheet } from 'react-native';

const BG = '#0A0F1E';
const CARD_BG = '#1A1F2E';
const BORDER = 'rgba(255,255,255,0.06)';
const GREEN = '#00C896';
const RED = '#FF4D4F';
const GRAY = '#666';


export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: BG,
    },
    scrollView: {
        flex: 1,
    },

    // Enhanced Header Styles
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        paddingTop: 35,
        borderBottomWidth: 1,
        borderBottomColor: BORDER,
        backgroundColor: '#0A0F1E',
    },
    coinInfoSection: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 16,
        backgroundColor: '#0A0F1E',
        borderBottomWidth: 1,
        borderBottomColor: BORDER,
    },
    backButton: {
        backgroundColor: 'rgba(35,40,52,0.95)',
        borderRadius: 30,
        padding: 12,
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },

    symbolContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    symbolIcon: {
        backgroundColor: 'rgba(247,147,26,0.1)',
        borderRadius: 20,
        padding: 8,
        marginRight: 12,
    },
    symbolInfo: {
        alignItems: 'flex-start',
    },
    symbolText: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 2,
    },
    symbolName: {
        color: GRAY,
        fontSize: 14,
    },
    priceContainer: {
        alignItems: 'center',
    },
    priceText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '600',
        marginBottom: 6,
    },
    changeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 12,
    },
    changeText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    favoriteButton: {
        padding: 8,
        backgroundColor: 'rgba(35,40,52,0.8)',
        borderRadius: 20,
    },

    // Enhanced Chart Section
    chartSection: {
        paddingHorizontal: 16,
        paddingVertical: 16,
    },
    timeframeTabs: {
        flexDirection: 'row',
        marginBottom: 16,
        backgroundColor: CARD_BG,
        borderRadius: 12,
        padding: 4,
        borderWidth: 1,
        borderColor: BORDER,
    },
    timeframeTab: {
        flex: 1,
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
        alignItems: 'center',
    },
    activeTimeframeTab: {
        backgroundColor: '#232834',
    },
    timeframeText: {
        color: GRAY,
        fontSize: 14,
        fontWeight: '500',
    },
    activeTimeframeText: {
        color: '#fff',
    },
    chartContainer: {
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: BORDER,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    chartHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    chartTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    chartControls: {
        flexDirection: 'row',
        gap: 8,
    },
    chartControl: {
        padding: 8,
        backgroundColor: 'rgba(35,40,52,0.8)',
        borderRadius: 8,
    },
    chartArea: {
        height: 200,
        position: 'relative',
    },
    chartLines: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    chartLine: {
        position: 'absolute',
        top: 40,
        left: 20,
        right: 20,
        height: 3,
        backgroundColor: GREEN,
        borderRadius: 2,
    },
    chartLine2: {
        position: 'absolute',
        top: 70,
        left: 40,
        right: 40,
        height: 2,
        backgroundColor: 'rgba(0, 200, 150, 0.7)',
        borderRadius: 1,
    },
    chartLine3: {
        position: 'absolute',
        top: 100,
        left: 60,
        right: 60,
        height: 2,
        backgroundColor: 'rgba(0, 200, 150, 0.5)',
        borderRadius: 1,
    },
    chartLine4: {
        position: 'absolute',
        top: 130,
        left: 80,
        right: 80,
        height: 1,
        backgroundColor: 'rgba(0, 200, 150, 0.3)',
        borderRadius: 1,
    },
    chartLine5: {
        position: 'absolute',
        top: 160,
        left: 100,
        right: 100,
        height: 1,
        backgroundColor: 'rgba(0, 200, 150, 0.2)',
        borderRadius: 1,
    },
    chartDots: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    chartDot: {
        position: 'absolute',
        top: 38,
        left: 20,
        width: 8,
        height: 8,
        backgroundColor: GREEN,
        borderRadius: 4,
    },
    chartDot2: {
        position: 'absolute',
        top: 68,
        left: 40,
        width: 6,
        height: 6,
        backgroundColor: GREEN,
        borderRadius: 3,
    },
    chartDot3: {
        position: 'absolute',
        top: 98,
        left: 60,
        width: 6,
        height: 6,
        backgroundColor: GREEN,
        borderRadius: 3,
    },
    chartDot4: {
        position: 'absolute',
        top: 128,
        left: 80,
        width: 4,
        height: 4,
        backgroundColor: GREEN,
        borderRadius: 2,
    },
    chartDot5: {
        position: 'absolute',
        top: 158,
        left: 100,
        width: 4,
        height: 4,
        backgroundColor: GREEN,
        borderRadius: 2,
    },
    priceLabels: {
        position: 'absolute',
        right: 0,
        top: 0,
        bottom: 0,
        justifyContent: 'space-between',
        paddingVertical: 10,
    },
    priceLabel: {
        color: GRAY,
        fontSize: 12,
        fontWeight: '500',
    },
    marketStats: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        marginBottom: 16,
    },
    statCard: {
        flex: 1,
        minWidth: '45%',
        backgroundColor: CARD_BG,
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
        alignItems: 'center',
    },
    statLabel: {
        color: GRAY,
        fontSize: 12,
        marginBottom: 6,
    },
    statValue: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },

    // Enhanced Trading Section
    tradingSection: {
        paddingHorizontal: 16,
        paddingVertical: 16,
        marginTop: -40, // Move buttons up more
    },
    tabContainer: {
        flexDirection: 'row',
        marginBottom: 16,
        backgroundColor: CARD_BG,
        borderRadius: 12,
        padding: 4,
        borderWidth: 1,
        borderColor: BORDER,
    },
    tab: {
        flex: 1,
        paddingVertical: 12,
        alignItems: 'center',
        borderRadius: 8,
    },
    activeTab: {
        backgroundColor: '#232834',
    },
    tabText: {
        color: GRAY,
        fontSize: 16,
        fontWeight: '600',
    },
    activeTabText: {
        color: '#fff',
    },
    orderTypeContainer: {
        flexDirection: 'row',
        marginBottom: 16,
        backgroundColor: CARD_BG,
        borderRadius: 12,
        padding: 4,
        borderWidth: 1,
        borderColor: BORDER,
    },
    orderTypeButton: {
        flex: 1,
        paddingVertical: 10,
        alignItems: 'center',
        borderRadius: 8,
    },
    activeOrderTypeButton: {
        backgroundColor: '#232834',
    },
    orderTypeText: {
        color: GRAY,
        fontSize: 14,
        fontWeight: '500',
    },
    activeOrderTypeText: {
        color: '#fff',
    },
    orderInterface: {
        flexDirection: 'row',
        gap: 12,
    },
    buySection: {
        flex: 1,
        padding: 20,
    },
    sellSection: {
        flex: 1,
        padding: 20,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    sectionTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    buyIcon: {
        backgroundColor: 'rgba(0, 200, 150, 0.2)',
        borderRadius: 12,
        padding: 6,
        marginRight: 8,
    },
    sellIcon: {
        backgroundColor: 'rgba(255, 77, 79, 0.2)',
        borderRadius: 12,
        padding: 6,
        marginRight: 8,
    },
    sectionTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    balanceText: {
        color: GRAY,
        fontSize: 12,
    },
    inputContainer: {
        marginBottom: 16,
    },
    inputLabel: {
        color: GRAY,
        fontSize: 12,
        marginBottom: 6,
        fontWeight: '500',
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#232834',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: BORDER,
    },
    priceInput: {
        flex: 1,
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    amountInput: {
        flex: 1,
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    currencyLabel: {
        color: GRAY,
        fontSize: 14,
        fontWeight: '500',
        marginLeft: 8,
    },
    totalContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingVertical: 12,
        borderTopWidth: 1,
        borderTopColor: BORDER,
    },
    totalLabel: {
        color: GRAY,
        fontSize: 14,
        fontWeight: '500',
    },
    totalValue: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    buyButton: {
        backgroundColor: GREEN,
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
    },
    buyButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    sellButton: {
        backgroundColor: RED,
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
    },
    sellButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },

    // Enhanced Order Book Section
    orderBookSection: {
        paddingHorizontal: 16,
        paddingVertical: 16,
        backgroundColor: CARD_BG,
        marginTop: 16,
        borderTopWidth: 1,
        borderTopColor: BORDER,
    },
    orderBookHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    orderBookTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    orderBookSettings: {
        padding: 8,
        backgroundColor: 'rgba(35,40,52,0.8)',
        borderRadius: 8,
    },
    orderBookContent: {
        backgroundColor: '#232834',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: BORDER,
    },
    orderBookTableHeader: {
        flexDirection: 'row',
        marginBottom: 12,
        paddingHorizontal: 8,
    },
    orderBookHeaderText: {
        color: GRAY,
        fontSize: 12,
        flex: 1,
        textAlign: 'center',
        fontWeight: '500',
    },
    sellOrders: {
        marginBottom: 12,
    },
    orderRow: {
        flexDirection: 'row',
        paddingVertical: 8,
        paddingHorizontal: 8,
        borderRadius: 6,
    },
    sellPrice: {
        color: RED,
        fontSize: 14,
        flex: 1,
        textAlign: 'center',
        fontWeight: '600',
    },
    buyPrice: {
        color: GREEN,
        fontSize: 14,
        flex: 1,
        textAlign: 'center',
        fontWeight: '600',
    },
    orderAmount: {
        color: '#fff',
        fontSize: 14,
        flex: 1,
        textAlign: 'center',
        fontWeight: '500',
    },
    orderTotal: {
        color: '#fff',
        fontSize: 14,
        flex: 1,
        textAlign: 'center',
        fontWeight: '500',
    },
    currentPriceRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: 'rgba(0, 200, 150, 0.1)',
        borderRadius: 8,
        marginVertical: 8,
        borderWidth: 1,
        borderColor: 'rgba(0, 200, 150, 0.2)',
    },
    currentPrice: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    currentPriceChange: {
        color: GREEN,
        fontSize: 16,
        fontWeight: '600',
    },
    buyOrders: {
        marginTop: 12,
    },
    // Dropdown Styles
    dropdownContainer: {
        backgroundColor: CARD_BG,
        borderRadius: 12,
        marginHorizontal: 16,
        marginTop: 8,
        borderWidth: 1,
        borderColor: BORDER,
        maxHeight: 300,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.16,
        shadowRadius: 8,
        elevation: 4,
    },
    dropdownScroll: {
        maxHeight: 280,
    },
    dropdownItem: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: BORDER,
    },
    selectedDropdownItem: {
        backgroundColor: 'rgba(0, 200, 150, 0.1)',
    },
    dropdownItemContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    dropdownItemIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: 'rgba(255,255,255,0.1)',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    dropdownItemText: {
        flex: 1,
    },
    dropdownItemSymbol: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 2,
    },
    dropdownItemName: {
        color: GRAY,
        fontSize: 12,
    },
}); 