import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#0A0F1E',
    },
    scrollContainer: {
        flex: 1,
    },
    scrollContentContainer: {
        paddingBottom: 40,
    },
    statusBarSpacing: {
        height: 44,
    },
    marginTextContainer: {
        marginHorizontal: 20,
        marginTop: 16,
        marginBottom: 8,
        flexDirection: 'row',
        alignItems: 'center',
    },
    stickyMarginTextContainer: {
        marginHorizontal: 20,
        marginTop: 16,
        marginBottom: 8,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#0A0F1E',
        paddingVertical: 8,
        zIndex: 10,
    },
    marginText: {
        color: '#aaa',
        fontSize: 14,
        fontWeight: 'bold',
        textAlign: 'left',
        lineHeight: 20,
        marginRight: 20,
    },
    marginTextButton: {
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 6,
    },
    spotText: {
        color: '#aaa',
        fontSize: 14,
        fontWeight: 'bold',
        textAlign: 'left',
        lineHeight: 20,
    },
    headerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 15,
    },
    headerScroll: {
        flex: 1,
    },
    headerTab: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        marginRight: 8,
        borderRadius: 20,
    },
    activeHeaderTab: {
        backgroundColor: '#00C896',
    },
    headerTabText: {
        color: '#CCCCCC',
        fontSize: 14,
        fontWeight: '500',
    },
    activeHeaderTabText: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    headerIcons: {
        flexDirection: 'row',
        gap: 15,
    },
    headerIcon: {
        padding: 4,
    },
    toggleSection: {
        marginHorizontal: 20,
        marginTop: 20,
        marginBottom: 24,
    },
    toggleLabel: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 16,
        textAlign: 'center',
    },
    toggleContainer: {
        flexDirection: 'row',
        backgroundColor: '#1A1F2E',
        borderRadius: 16,
        padding: 2,
    },
    toggleButton: {
        flex: 1,
        borderRadius: 14,
        paddingHorizontal: 18,
        paddingVertical: 6,
        marginRight: 2,
        alignItems: 'center',
    },
    activeToggleButton: {
        backgroundColor: '#232834',
    },
    toggleText: {
        color: '#aaa',
        fontWeight: 'bold',
        fontSize: 15,
    },
    activeToggleText: {
        color: '#FFFFFF',
    },
    greenBar: {
        alignSelf: 'center',
        width: 16,
        height: 2,
        backgroundColor: '#00C896',
        marginTop: 2,
        borderRadius: 1,
    },
    amountSectionContainer: {
        backgroundColor: '#1A1F2E',
        marginHorizontal: 20,
        marginBottom: 24,
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.06)',
    },
    amountLabel: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 16,
    },
    amountContainer: {
        paddingHorizontal: 20,
        marginBottom: 20,
    },
    amountRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    amountText: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#FFFFFF',
    },
    currencyContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1A1F2E',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
    },
    currencyText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        marginRight: 4,
    },
    dropdownOverlay: {
        position: 'absolute',
        top: 100,
        left: 20,
        right: 20,
        zIndex: 10,
    },
    dropdownContainer: {
        backgroundColor: '#1A1F2E',
        borderRadius: 12,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.06)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    dropdownItem: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.06)',
    },
    dropdownItemActive: {
        backgroundColor: '#232834',
    },
    dropdownItemText: {
        color: '#CCCCCC',
        fontSize: 14,
        fontWeight: '500',
    },
    dropdownItemTextActive: {
        color: '#00C896',
        fontWeight: '600',
    },
    usdtRow: {
        marginTop: 0,
    },
    usdtContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: 'rgba(0, 200, 150, 0.1)',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        alignSelf: 'flex-start',
    },
    usdtText: {
        color: '#00C896',
        fontSize: 14,
        fontWeight: '600',
    },
    minimumAmountContainer: {
        marginTop: 8,
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: 'rgba(255,77,79,0.1)',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,77,79,0.2)',
    },
    minimumAmountText: {
        color: '#FF4D4F',
        fontSize: 12,
        fontWeight: '500',
        textAlign: 'center',
    },
    sectionContainer: {
        backgroundColor: '#1A1F2E',
        marginHorizontal: 20,
        marginBottom: 8,
        borderRadius: 12,
        padding: 16,
    },
    paymentSectionContainer: {
        backgroundColor: '#1A1F2E',
        marginHorizontal: 20,
        marginBottom: 24,
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.06)',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    sectionLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    paymentInfo: {
        flex: 1,
    },
    chevronContainer: {
        backgroundColor: 'rgba(0, 200, 150, 0.15)',
        borderRadius: 12,
        padding: 8,
        marginLeft: -8,
        borderWidth: 1,
        borderColor: 'rgba(0, 200, 150, 0.2)',
        shadowColor: '#00C896',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    cryptoIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#00C896',
        alignItems: 'center',
        justifyContent: 'center',
    },
    cryptoIconText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
    paymentIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#232834',
        alignItems: 'center',
        justifyContent: 'center',
    },
    sectionTitle: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    paymentMethod: {
        color: '#CCCCCC',
        fontSize: 14,
        marginTop: 2,
    },
    modalOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    modalBlur: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: '#181E2A',
        borderRadius: 20,
        padding: 24,
        marginHorizontal: 20,
        width: width - 40,
        maxHeight: height * 0.7,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 16,
        elevation: 10,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.08)',
    },
    modalTitle: {
        color: '#FFFFFF',
        fontSize: 20,
        fontWeight: 'bold',
    },
    closeButton: {
        padding: 4,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.1)',
    },
    paymentMethodsList: {
        marginBottom: 24,
    },
    paymentMethodItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 16,
        paddingHorizontal: 16,
        borderRadius: 12,
        marginBottom: 8,
        backgroundColor: '#232834',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
    },
    paymentMethodItemActive: {
        backgroundColor: 'rgba(0,200,150,0.1)',
        borderColor: 'rgba(0,200,150,0.3)',
    },
    paymentMethodItemDisabled: {
        backgroundColor: '#1A1F2E',
        borderColor: 'rgba(255,255,255,0.04)',
        opacity: 0.6,
    },
    paymentMethodLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    paymentMethodIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: 'rgba(255,255,255,0.1)',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    paymentMethodIconConnected: {
        backgroundColor: 'rgba(255,255,255,0.1)',
    },
    paymentMethodIconDisabled: {
        backgroundColor: 'rgba(255,255,255,0.05)',
    },
    paymentMethodInfo: {
        flex: 1,
    },
    paymentMethodText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '500',
    },
    paymentMethodTextActive: {
        color: '#00C896',
        fontWeight: '600',
    },
    paymentMethodTextDisabled: {
        color: '#666',
    },
    paymentMethodStatus: {
        fontSize: 12,
        marginTop: 2,
    },
    paymentMethodStatusConnected: {
        color: '#00C896',
    },
    paymentMethodStatusDisabled: {
        color: '#666',
    },
    cancelButton: {
        backgroundColor: '#2A2F3E',
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
    },
    cancelButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    actionButton: {
        backgroundColor: '#00C896',
        marginHorizontal: 20,
        marginBottom: 20,
        paddingVertical: 18,
        borderRadius: 16,
        alignItems: 'center',
        shadowColor: '#00C896',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    actionButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    keypadContainer: {
        paddingHorizontal: 20,
        paddingBottom: 20,
        marginTop: 20,
    },
    keypadRow: {
        flexDirection: 'row',
        marginBottom: 8,
    },
    keypadButton: {
        flex: 1,
        height: Math.min(60, height * 0.08),
        backgroundColor: 'transparent',
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 2,
    },
    keypadText: {
        color: '#FFFFFF',
        fontSize: Math.min(24, width * 0.06),
        fontWeight: '500',
    },
}); 